Makefile

Update the Makefile to allow for errors in the controller-kind, as the stage is used to load the images into the kind cluster for testing before the helm chart has been deployed

Allow for controller-kind errors

---

pkg/assets/job.yaml.tpl

Probably creeped in during testing; decreasing back to 3

[BUGFIX] - Decreasing Backoff Limit

---

pkg/apis/terraform/v1alpha1/provider_types.go
pkg/handlers/providers/validation.go
pkg/handlers/providers/validation_test.go

Fixing up the supported providers as these copied in as `provider "{{ .Name }}"` into the terraform

[FIX] - Supported Providers

---

pkg/assets/assets_test.go
pkg/assets/job.yaml.tpl
pkg/controller/configuration/delete.go
pkg/controller/configuration/ensure.go
pkg/controller/configuration/reconcile_test.go
pkg/utils/jobs/jobs.go

We were not correctly retrieving the service account from the provider and was incorrectly choosing the service account.
- Defaulting the service account to the terraform-executor
- Using the provider service account is defined and source injected
- Added unit tests to ensure it doesn't happen again
- Added checks on the job template and assets

[BUGFIX] - Provider Service Accounts

---

charts/crds/terraform.appvia.io_providers.yaml
pkg/apis/terraform/v1alpha1/provider_types.go
pkg/apis/terraform/v1alpha1/zz_generated.deepcopy.go
pkg/assets/assets_test.go
pkg/controller/configuration/ensure.go
pkg/controller/configuration/reconcile_test.go
pkg/handlers/configurations/validation.go
pkg/handlers/configurations/validation_test.go
pkg/handlers/providers/validation_test.go
pkg/register/assets.go
pkg/utils/labels.go
pkg/utils/labels_test.go

The support adds the support to control who can access providers based on namespace and resource labelling
The provider now have a `spec.selector` which can specify namespace and resource labels selectors. These are checks against the requesting configuration and if they don't matched, the request to use the provider is denied.
```yaml
---
kind: Provider
metadata:
name: default-irsa
spec:
selector:
namespace:
matchLabel:
name: apps
matchExpressions:
- key: name
operator: In
values: [apps]
serviceAccount: terraform-executor
source: injected
provider: aws
```
289f936 [FEATURE] Provider RBAC
c5cc9b2 - updating the controller to check the provider rbac is sounds
841c44d - adding a handler to check the configuration crd and provider rbac
38fb4a1 - …

[FEATURE] - Provider RBAC

---

.github/workflows/release.yaml
charts/crds/terraform.appvia.io_providers.yaml
charts/values.yaml
pkg/apis/terraform/v1alpha1/provider_types.go
pkg/register/assets.go

Fixing a silly mistake found from the e2e ticket

[BUGFIX] - Provider Enum on API Types

---

examples/policy.yaml
pkg/apis/terraform/v1alpha1/constraint_types.go
pkg/handlers/configurations/validation.go
pkg/handlers/configurations/validation_test.go
pkg/handlers/policies/validation.go
pkg/handlers/policies/validation_test.go

The current module constraint is global, adding a selector here you can target specific
resources or namespaces and provides a means for additional permissions. Note as with all
selectors here, a empty selector indicates it applies to all.

[FEATURE] - Module Selector

---

.github/workflows/ci.yaml
.github/workflows/latest.yaml
.github/workflows/release.yaml

Some changes to the way the workflows work
- dropped the need to run ci on anything other than a PR given we force it on all PR and force linear history
- moved the helm deploy into the master merge to catch non-tagged related changes

[BUILD] - Changing Workflow

---

.github/workflows/latest.yaml

We should ignore any releases which are already existing

[HELM] - Ignore Existing Releases

---

.github/workflows/e2e.yaml
pkg/controller/configuration/ensure.go
pkg/utils/terraform/types.go

The terraform state can be a little more complicated; since we don't
care about complex types at the moment we can write the output as is and
not try and do any extra decoding.

[BUGFIX] - Terraform State Decoding

---

.github/workflows/latest.yaml

The helm release job doesn't need to wait on the release images as they are not connected

[BUILD] - Latest Workflow Change

---

charts/terraform-controller/crds/terraform.appvia.io_policies.yaml
pkg/apis/terraform/v1alpha1/constraint_types.go
pkg/register/assets.go

The <NAME> is causing an error when generating the api reference documentation; it's not really required so we can drop it

[API] - Description on API Types

---

pkg/utils/jobs/jobs.go
test/e2e/integration/apply.bats
test/e2e/integration/plan.bats

We add the labels to the job but these aren't carried through to the pods. This PR adds the labels on both.
Also adding extra e2e tests to ensure the logs are viewable

[FEATURE] - Adding Pod Labels

---

.github/workflows/ci.yaml

The timeout on linting currently set to 2m is occasionally hitting the
limit and causing failed runs. Bumping the timeout to 4 minutes.

Fix linting timeout

---

pkg/apis/terraform/v1alpha1/configuration_types.go
pkg/controller/configuration/ensure.go
pkg/controller/configuration/reconcile_test.go
test/e2e/integration/apply.bats
test/fixtures/state.go

Currently the terraform version is not exposed to the developers so
though they can override the version they would have to ask the platform
team or view the logs to know the version. With this PR the version of
terraform is applied to the status

[FEATURE] - Adding Terraform Version to Status

---

pkg/controller/configuration/ensure.go

Fixing a bug where if you leave an approval annotation on a autoApproval configuration the annotation is taking precedence

[BUGFIX] - Approval Annotation

---

.github/workflows/ci.yaml
Makefile

Dropping the need to filter out the crdtest directory from the go test stage

[BUILD] - CI Workflow

---

.github/workflows/e2e.yaml

Adding the deployment key secret to the e2e list, this is used to verify private repositories

[E2E] - Deployment Key Secret

---

.github/workflows/e2e.yaml

Allowing us to determine the controller version to run in the e2e, by
default we use 'ci', which also means we build the images locally.
Essentially I want to be able to trigger: `gh run workflow` and specify a specific tag to use.

[E2E] - Controller Version

---

pkg/cmd/tnctl/workflow/assets/github/ci.yaml.tpl
pkg/cmd/tnctl/workflow/assets/github/main.yaml.tpl

Generating the workflow to take into account no files in the base reference

[CLI] - Infracost Workflow

---

pkg/cmd/search/terraform/registry.go
pkg/cmd/search/terraform/registry_test.go

The namespaces documented on the terraform registry look like http://registry.terraform.io/namespace/<NAME>. We should choose to keep this arrangement so it's easy to copy and paste

[FEATURE] - Terraform Registry Namespace

---

charts/terraform-controller/templates/deployment.yaml
charts/terraform-controller/values.yaml
cmd/controller/main.go
pkg/assets/job.yaml.tpl
pkg/controller/configuration/controller.go
pkg/controller/configuration/delete.go
pkg/controller/configuration/ensure.go
pkg/controller/configuration/reconcile_test.go
pkg/server/server.go
pkg/server/types.go
pkg/utils/jobs/jobs.go

Currently unless you override the template there is no way of the platform team getting
additional secrets in the execution of the terraform jobs. With this PR we've added
a command line options --executor-secret which is always added into the executor
terraform container.

[FEATURE] - Additional Controller Secrets

---

charts/terraform-controller/Chart.yaml
charts/terraform-controller/values.yaml

Updating the default webhooks port to 10250 as out of the box it's supported by EKS

[HELM] - Webhooks Port

---

pkg/apiserver/handlers.go
pkg/apiserver/server_test.go

Currently the pods used to watch the execution logs in the developer namespace can be a little slow,. This is due to the http.ResponseWriter buffering the output. With this PR we check for a http.Flusher interface and flush the logs line by line, making the feedback quickier. This is especially useful on long running configurations such as those for RDS's

[BUGFIX] - Streaming Logs

---

pkg/cmd/tnctl/describe/assets/describe.yaml.tpl

The values for the costs can be empty thus you need to ensure a default

[BUGFIX] - CLI Describe Template

---

pkg/cmd/factory.go
pkg/cmd/tnctl/logs/logs.go
pkg/cmd/tnctl/tnctl.go

Currently to retrieve the plan or apply logs for a configuration the user must list all the pods, find the
one matching the generation and stage and then kubectl logs the pods. This command simply wraps that requirement
and makes the task quicker

[CLI] - Adding Logs Command

---

pkg/apiserver/handlers.go

We introduced a bug in a previous PR (should have run the E2E). Was using the incorrect name

[BUGFIX] - User Inputs Parameter Checking

---

charts/terraform-controller/templates/rbac.yaml
charts/terraform-controller/values.yaml

We should allow the service account in the controller namespace permissions to run as executors, this makes the ability to deploy multiple service account easier
By default all service account used by an executor (i.e lets assume you want to use multiple injected identities) need RBAC permissions to lease and secrets in the controller namespace i.e. 
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
name: {{ include "terraform-controller.fullname" . }}-executor
rules:
- apiGroups:
- coordination.k8s.io
resources:
- leases
verbs:
- create
- delete
- get
- list
- update
- watch
- apiGroups:
- ""
resources:
- configmaps
verbs:
- get
- list
- watch
- apiGroups:
- ""
resources:
- secrets
verbs:
- create
- delete
- get
- list
- patch
- update
- watch
```
If you create …

[HELM] - Service Account Permissions - Executors

---

charts/terraform-controller/templates/providers.yaml
charts/terraform-controller/values.yaml

At present to deploy a provider it must be done out-of-baud from the helm chart. With this PR you can adding a collection of Providers which will deploy along aside the chart
Example for creating and IRSA 
```yaml
---
rbac:
executor:
annotations:
eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ROLE
providers:
- source: injected
provider: aws
serviceAccount: terraform-executor
```

[HELM] - Deploy Providers via Helm

---

charts/terraform-controller/templates/policies.yaml
charts/terraform-controller/values.yaml

Adding the ability to deploy policies via the helm chart
```yaml
policies:
- name: permitted-modules
constraint:
modules:
allowed:
- "https://github.com/appvia/*"
```

[HELM] - Deploy Policies via Helm Chart

---

pkg/controller/configuration/detect_errors.go

We introduced a bug in the last commit - the output of this method should always be do not move forward

[BUGFIX] - Refuse to continue

---

.github/workflows/images.yaml

We forgot to update the prefix for the docker images in the workflow

[CI] - Workflow Fix - Docker Images

---

charts/terranetes-controller/templates/providers.yaml
charts/terranetes-controller/values.yaml

The ability to define the provider summary field was missing from the helm chart template

[FEATURE] - Support Summaries on Provider Helm Chart

---

charts/terranetes-controller/templates/deployment.yaml
charts/terranetes-controller/values.yaml
cmd/controller/main.go
pkg/assets/job.yaml.tpl
pkg/controller/configuration/controller.go
pkg/controller/configuration/ensure.go
pkg/controller/configuration/reconcile.go
pkg/controller/configuration/reconcile_test.go
pkg/server/server.go
pkg/server/types.go
pkg/utils/jobs/jobs.go
pkg/utils/terraform/utils.go
test/fixtures/state.go

Currently we only support kubernetes as a backend for the terraform state of the Configuration. This this PR
we've introduced the ability to define a custom template and support any backend supported by Terraform.
- updated the helm chart to support backendTemplate
- added a new --backend-template to the controller
- added the unit tests and checks (missing e2e for now)
- updated the job template to upload the terraform state
You can upload a kubernetes secret such as 
```yaml 
terraform {
backend "s3" {
bucket     = "terranetes-controller-state"
key        = "cluster_one/{{ .namespace }}/{{ .name }}
region     = "eu-west-2"
access_key = "AWS_ACCESS_KEY_ID"
secret_key = "AWS_SECRET_ACCESS_KEY"
}
}
```
```bash 
kubectl -n terraform-system create secret generic backend …
```

[FEATURE] - Custom State Backend

---

pkg/cmd/factory.go
pkg/cmd/tnctl/search/search.go

On saving the configuration file we were not checking the directory structure existed. Also when passing a --source option to the search we were checking the source was available in the configuration

[BUGFIX] - CLI Configuration

---

pkg/cmd/search/github/github.go

At present we only take into account the description and the topics when searching for terms. With this PR we also using the name of the repository as well

[FEATURE] - Using Repository Name in Search

---

charts/terranetes-controller/Chart.yaml
charts/terranetes-controller/templates/policies.yaml
charts/terranetes-controller/templates/providers.yaml

There is a bug in the template for the policies and providers which is causing the seperator to be place into the wrong place
When running `helm upgrade --install -n terraform-system terranetes charts/terranetes-controller/ --create-namespace --values dev/my_values.yaml --dry-run`
I was getting the following
```YAML
kind: Provider
metadata:
name: aws
annotations:
labels:
spec:
source: injected
provider: aws
serviceAccount: terraform-executor---
kind: Provider
metadata:
name: azure
annotations:
labels:
spec:
source: injected
provider: azure
serviceAccount: terraform-executor
```
Post the change we go to 
```YAML
---
kind: Provider
metadata:
name: aws
annotations: …
```

[HELM] - Bugfix Helm Template (Policies & Providers)

---

cmd/step/main.go
cmd/step/types.go
images/Dockerfile.executor
pkg/assets/job.yaml.tpl
pkg/controller/configuration/reconcile_test.go

Currently we use kubectl in the executor to upload any assets required into kubernetes secrets - i.e. the cost report, terraform state and so forth. In this pull request added a new --upload command line which performs this requirement for us in the step command. On success completion any files will be uploaded.

[FEATURE] - Removing Kubectl from Executor Image

---

pkg/cmd/factory_test.go
pkg/controller/configuration/ensure.go
pkg/handlers/configurations/validation.go
pkg/utils/kubernetes/labels.go
pkg/utils/kubernetes/labels_test.go
pkg/utils/kubernetes/time.go
pkg/utils/kubernetes/time_test.go

This pull request is purely to move methods around to isolate the dependenicies a little better.
- moved anything related to kubernetes into pkg/utils/kubernetes package
- removed the unrequired factory method NewFactoryWithClient as it can be done with options

[CLEAN] - Dependencies Shuffle

---

pkg/apis/core/v1alpha1/status_types.go
pkg/controller/configuration/metrics.go
pkg/controller/configuration/reconcile.go

Currently we do not have a prometheus metrics for the status of the configuration. This this change we've introduced a configuration_status can which can be used to track and trigger on Configuration which have errors

[FEATURE] - Configuration Status Metrics

---

charts/terranetes-controller/values.yaml

Bumping the default image of infracost to v0.10.9 from v0.10.8

[IMAGES] - Bumping Infracost to v0.10.9

---

charts/terranetes-controller/templates/deployment.yaml
charts/terranetes-controller/values.yaml
cmd/controller/main.go
pkg/controller/configuration/controller.go
pkg/controller/configuration/ensure.go
pkg/controller/configuration/reconcile_test.go
pkg/server/types.go
test/e2e/integration/infracost.bats

Currently terraform modules used by the controller has no means of gather context from the Configuration itself - i.e. namespace, name, labels and so forth. It can be useful to have these detail however, so instance prefixing configuration with namespace name or adding tags. In the change we've introduce an --enable-context-injection which optional turns on the feature and injects a map into the terraform module terranetes.{} with name and namespace attributes

[FEATURE] - Context Injection

---

charts/terranetes-controller/values.yaml

Bumping the default image for checkov to use from 2.1.67 to 2.1.104

[IMAGES] - Bumping Checkov to 2.1.104

---

pkg/cmd/tnctl/describe/assets/describe.yaml.tpl

A field in the describe command was slightly missaligned in the template

[BUGFUX] - CLI Describe Template

---

pkg/cmd/tnctl/build/build.go
pkg/cmd/tnctl/search/search.go

Adding a -o|--output to the search command to redirect the output from the command
to a specified file rather than the default stdout

[FEATURE] - Redirect Generated Configuration to file

---

pkg/assets/job.yaml.tpl

Making the checkov configuration optional given the external source

[BUGFIX] - Checkov Configuraion Optional

---

images/Dockerfile.controller
images/Dockerfile.executor

Upgrading the base image of the controller and executor to alpine 3.16

[BUILD] - Upgrading Base Image (Alpine 3.15 -> 3.16)

---

pkg/cmd/tnctl/logs/logs.go

Currently the tnctl logs only watches the apply and plan. With this change the logs
will also watch the destroy logs as well

[FEATURE] - Watching Destroy Logs

---

test/e2e/integration/cloud/aws/plan.bats

When moving to terraform 1.2.7 the current aws module we were using for the bucket was failing.
I've bumped the version of the module from 0.3.1 to 0.3.3

[E2E] - Bug Fixes in E2E

---

charts/terranetes-controller/values.yaml

Experiencing issues with our E2E modules, not sure why they are kicked up a fuss but
dont have the time to look at the moment

[IMAGES] - Terraform Image Version Downgrade (1.2.7 -> 1.2.5)

---

.github/workflows/versions.yaml

The repository and the image are different so we can't use repository here

[CI] - Bridgecrew Image Versions

---

images/Dockerfile.cli

Bumping the base image of the CLI to Alpine 3.16

[IMAGES] - Bumping the CLI Base Image (3.15 -> 3.16)

---

charts/terranetes-controller/templates/rbac.yaml
charts/terranetes-controller/templates/serviceaccount.yaml
charts/terranetes-controller/values.yaml
cmd/controller/main.go
docs/development.md
examples/provider.yaml
pkg/controller/configuration/reconcile_test.go
pkg/utils/jobs/jobs.go

Switching the name of the account to terranetes executor inline with the rest of the
service accounts

[BUILD] - Executor Service Account to terranetes-executor

---

pkg/apiserver/handlers.go
test/e2e/check-suite.sh
test/e2e/integration/error-handler.bats

When the job has an issue in the init stage the logs aren't appearing to the user. With this
PR we correctly end on a failed pod and render the logs to the user.
- added a e2e check to ensure the logs are functioning correctly

[BUGFIX] - Init Errors Showing in Logs

---

pkg/apis/terraform/v1alpha1/configuration_types.go
pkg/controller/configuration/delete.go

Currently we continue to requeue the controller even when the deletion has failed and no retries
will be attempted. This leaves the controller printing out errors messages every 30s. It would be
better to admit defeat and highlight to the user

[BUGFIX] - Configuration Deletion

---

README.md

This doesn't appear to work as expected - with the tag remaining out of date

[DOCS] - Removing Tag Badge

---

.golangci.yml
go.mod
go.sum
pkg/apis/terraform/v1alpha1/configuration_types.go
pkg/assets/job.yaml.tpl
pkg/controller/configuration/delete.go
vendor/github.com/onsi/gomega/CHANGELOG.md
vendor/github.com/onsi/gomega/RELEASING.md
vendor/github.com/onsi/gomega/gomega_dsl.go
vendor/github.com/onsi/gomega/internal/async_assertion.go
vendor/github.com/onsi/gomega/internal/gomega.go
vendor/github.com/onsi/gomega/matchers.go
vendor/github.com/onsi/gomega/matchers/be_key_of_matcher.go
vendor/github.com/onsi/gomega/types/types.go
vendor/modules.txt

Linters 'deadcode', 'varchar' and 'structcheck' have all been deprecated and
replaced by 'unused'.

[BUILD] - Removing Deprecated Linters

---

pkg/cmd/tnctl/kubectl/plugin.go

The hash is creating a h1 header in the markdown and messing up the CLI docs for this page

[DOCS] - Fixing CLI Reference Docs

---

.github/workflows/e2e.yaml

Bumping the version to v3 as node 12 actions are deprecated

[BUILD] - Github Action Update (Upload Artifacts)

---

charts/terranetes-controller/values.yaml
images/Dockerfile.executor
images/assets/watch_logs.sh
pkg/controller/configuration/helper.go
pkg/controller/configuration/reconcile_test.go
pkg/utils/jobs/jobs.go

**Desired behaviour:**
- Retry if the [Terranetes controller cannot be reached](https://github.com/appvia/terranetes-controller/pull/493/files#diff-daf24424c5712e22bd0c8e200b5496ef4167be92fd8d4a411d713b07e506785aR70)
- Retry if the Terranetes controller was [unable to retrieve logs from the executor pod](https://github.com/appvia/terranetes-controller/pull/493/files#diff-daf24424c5712e22bd0c8e200b5496ef4167be92fd8d4a411d713b07e506785aR63) (the one performing the tf plan, apply, checkov tests etc)
- Return a non-zero exit code and don't retry / restart the watcher pod if the log output shows a failure of some sort:
- A [log error was detected](https://github.com/appvia/terranetes-controller/pull/493/files#diff-daf24424c5712e22bd0c8e200b5496ef4167be92fd8d4a411d713b07e506785aR87-R90)
- The …

[BUGFIX] - Wrap log watcher Pod with error handling and retry logic

---

pkg/cmd/tnctl/describe/assets/describe.yaml.tpl
pkg/controller/configuration/ensure.go
pkg/controller/configuration/reconcile_test.go

When security policies produces zero matches on passes and fails the report was not matching the expected out.
- Adjusted the controller to permit a zero matching report
- Adjusted the tnctl describe to support as well

[BUGFIX] - Checkov Policies Zero Matches

---

pkg/controller/configuration/reconcile_test.go
pkg/utils/terraform/utils.go
pkg/utils/terraform/utils_test.go

The kubernetes backend for terraform supports labels which can be useful for filtering out the state to Configuration. This PR adds those labels to the secret created by terraform.

[FEATURE] - Kubernetes Backend Secret Labels

---

pkg/cmd/helper.go
pkg/cmd/tnctl/search/search.go
pkg/cmd/tnctl/state/clean.go
pkg/cmd/tnctl/state/helper.go
pkg/cmd/tnctl/state/list.go
pkg/cmd/tnctl/state/list_test.go
pkg/cmd/tnctl/state/state.go
pkg/cmd/tnctl/state/suite_test.go
pkg/cmd/tnctl/tnctl.go

This PR adds the tnctl state list|clean commands which can be used to show the matching configuration and secrets. The
clean command provide spring cleaning, removing any orphaned secrets

[FEATURE] - Kubernetes State Command

---

pkg/controller/configuration/ensure.go
pkg/controller/configuration/reconcile_test.go
pkg/controller/ensure.go

The ready state needed to be reset in between the plan and the apply. The bug allowed
for error conditions to linger on the ready condition which were no longer valid i.e https://github.com/appvia/terranetes-controller/issues/525

[BUGFIX] - Fixing Ready Condition Transition

---

pkg/handlers/configurations/validation.go
pkg/handlers/configurations/validation_test.go
test/e2e/integration/constraints/modules.bats

The current message which is thrown when a Configuration violates a module security policy can be confusing. Trying to make the source of the error more clear.

[BUILD] - Change Module Security Restriction Message

---

charts/terranetes-controller/templates/deployment.yaml
cmd/controller/main.go
pkg/controller/configuration/controller.go
pkg/controller/policy/controller.go
pkg/controller/provider/controller.go
pkg/server/server.go
pkg/server/types.go

At present setting the --enable-webhooks to false throws an error as the controller runtime appears to register the server regardless. This PR fixes the issue by passing the setting down to any registration code

[BUGFIX] - Enable Webhooks Togggle

---

pkg/assets/job.yaml.tpl

Adding the environment variable to disable checking for updates in the CLI breakdown of infracosts

[BUGFIX] - Disable Infracosts Update Check

---

Makefile

Changing from a recursive copy to a sync command when retrieving the logs from S3 diagnostic bucket

[E2E] - Syncing Diagnostics Logs

---

pkg/controller/configuration/controller.go
pkg/controller/configuration/ensure.go
pkg/controller/configuration/reconcile.go

The predicator can cause weird behavour - its safer to move this into an ensureFunc()

[BUGFIX] - Reconcilation Annontation Predicate moved into Ensure Func

---

.github/workflows/e2e.yaml

Fixing the extra word in the run name of the workfow

[E2E] - Workflow Run Name Typo

---

charts/terranetes-controller/Chart.yaml

Appears the releases of v0.3.14 was somewhat messed up due to changes in the Github pipeline. Bumping a version now to republish the chart

[HELM] - Release v0.3.14

---

.github/workflows/e2e.yaml
charts/terranetes-controller/templates/policies.yaml
charts/terranetes-controller/values.yaml
examples/policy.yaml
pkg/apis/terraform/v1alpha1/policy_types.go
pkg/assets/job.yaml.tpl
pkg/controller/configuration/ensure.go
pkg/controller/configuration/reconcile.go
pkg/controller/configuration/reconcile_test.go
pkg/handlers/configurations/mutation.go
pkg/handlers/configurations/mutation_test.go
pkg/handlers/policies/validation.go
pkg/handlers/policies/validation_test.go
pkg/utils/jobs/jobs.go

At present we only allow for injecting defaults into a configuration - it would be nice however to inject secret based on a selector as well. For example the ability to support the platform team managing the deployment keys for private repositories. 
Lets take the following example - 
* The platform have a number of private repositories which need authentication to consume. 
* They don't want the developers to care about the authentication, it should be transparent to them.
* They have created a kubernetes secret in the controller namespace container a deployment key
* They want the x number of modules to use the ssh-key to clone by default
```yaml
---
kind: Policy
metadata:
name: environment-defaults
spec:
defaults:
- selector:
namespace: …
```

[FEATURE] - Adding Default Secrets into Policy

---

.github/workflows/e2e.yaml

The save step is constantly failing - changing to v3 to see if the errors have been fixed

[BUILD] - Changing to v3 Save Github Actions

---

pkg/apis/terraform/v1alpha1/provider_types.go
pkg/handlers/configurations/mutation.go
pkg/handlers/configurations/mutation_test.go
pkg/handlers/providers/validation.go
pkg/handlers/providers/validation_test.go

This feature enabled platform administrators to set a Provider as default via an annotation. For Configuration's which have not specified the `spec.providerRef.name`, the default is automatically added. Validation has also been added to ensure only one Provider is default at any one time.
```yaml
---
kind: Provider
metadata:
name: aws
annotations: 
terranetes.appvia.io/default-provider: "true"
spec:
source: secret
provider: aws
secretRef:
namespace: terraform-system
name: aws
````

[FEATURE] - Default Providers

---

pkg/assets/job.yaml.tpl

Workload identity in Azure via AAD is performed via a binding, using a podselector https://azure.github.io/aad-pod-identity/docs/concepts/azureidentitybinding/#azureidentitybindingspec .. This requires a specific label `aadpodidbinding` on all job pods

[BUGFIX] - Azure Identity Binding

---

pkg/server/webhooks.go

A previous feature added the toggle around enabling namespace protection, ensuring namespace's with Configuration resources are blocked from deletion until the resource is deleted

[FEATURE] - Delection of Namespace Protection Webhook

---

pkg/utils/terraform/utils.go

If features is not configured, we should add an empty map to satistfy provider

[BUGFIX] - Azure Features

---

charts/terranetes-controller/crds/terraform.appvia.io_configurations.yaml
charts/terranetes-controller/crds/terraform.appvia.io_policies.yaml
charts/terranetes-controller/crds/terraform.appvia.io_providers.yaml
pkg/apis/terraform/v1alpha1/configuration_types.go
pkg/controller/configuration/ensure.go
pkg/controller/configuration/reconcile_test.go
pkg/register/assets.go

Currently there is no way to remap the inputs from a secret into a new name. Lets take the example were you have a secret containing DB_HOST but you want to use `database_hostname` as the input to the module. With this PR users now have the ability to remap the inputs as they see fit
```yaml
apiVersion: v1
kind: Secret
metadata:
name: mysecret
data:
DB_HOST: value
```
You can use in the Configuration as `database_hostname` like
```yaml
kind: Configuration
metadata:
name: bucket
spec:
module: https://github.com/terraform-aws-modules/terraform-aws-rds.git?ref=v3.1.0
providerRef:
name: aws
valueFrom:
- secret: mysecret
key: DB_HOST
remapped: database_hostname
optional: false
```

[FEATURE] - Allowing for Remapping of ValueFrom Inputs

---

examples/configuration.yaml
pkg/apis/terraform/v1alpha1/configuration_types.go
pkg/controller/configuration/ensure.go
pkg/controller/configuration/reconcile_test.go

A previous feature added the ability to override the name of the variable when sourced from a secret (https://github.com/appvia/terranetes-controller/pull/723). The field felt wrong and so we renamed it to 'name' instead.

[FEATURE] - Renaming ValueFrom Secret Name

---

test/e2e/integration/clean-protection.bats
test/e2e/integration/custom-state-backend.bats
test/e2e/integration/setup.bats

[E2E] - Fixing E2E Build

---

charts/terranetes-controller/templates/backend.yaml
charts/terranetes-controller/templates/deployment.yaml
charts/terranetes-controller/values.yaml
test/e2e/integration/custom-state-backend.bats

Extending the helm chart to allow for the creation of the backend secret

[HELM] - Custom Backend Secret

---

.github/workflows/ci.yaml

Adding the 'make preload' to the Github action when testing binary builds

[CI] - Adding Preload to Binary Builds

---

pkg/controller/preload/ensure.go
pkg/controller/preload/reconcile_test.go

Fixing a bug where when the provider on first install is configured with preload but the condition is not available on the status yet

[BUGFIX] - Conditions Not Available

---

pkg/controller/preload/controller.go

Currently the preload controller is only set to reconcile on the generation change which is causing the status to update late. We can change this to resource version and just need to be careful around how the provider controller is configured not to create a loop

[BUILD] - Preload Controller, Reconcile on Revision Change

---

cmd/source/source.go
cmd/source/source_test.go

Fixing the source to correctly handle submodules
This can easily be tested localy via
```shell
$ git checkout <BRANCH>
$ make source
$ export GIT_USERNAME=user or export GIT_PASSWORD
$ bin/source -d /tmp -s URL
$ export GIT_PASSWORD=PATH
$ bin/source -s git::https://dev.azure.com/gambol99/terranetes-controller/_git/e2e//module/submodule -d ./tmp
```

[BUGFIX] - Submodules Source Fix

---

pkg/assets/job.yaml.tpl
pkg/controller/configuration/reconcile_test.go

Currently when using the https://terranetes.appvia.io/terranetes-controller/admin/secrets/ command these secrets are not available to the setup init step, which makes it hard to use them as a common token auth private repositories

[BUGFIX] - Additional Secrets in Setup Stage

---

pkg/controller/configuration/delete.go
pkg/controller/configuration/delete_test.go

When using policies to inject the secrets, there was a bug where the additional secret was not being injected in the Deletion stage. I've fixed the error and introduced coverage

[BUGFIX] - Policy Injected Secrets not in Deletion Stage

---

Makefile

Fixing the 'coverage' stage in the makefile was missing packages and adding profile to general tests

[BUILD] - Makefile Coverage Stage

---

charts/terranetes-controller/templates/providers.yaml
charts/terranetes-controller/values.yaml

Configuration block is already supported in the Provider CRD however there was no support in the helm chart.  This adds the ability to specify a configuration block in Provider resources when using helm

[HELM] Support for provider configuration in helm chart

---

charts/terranetes-controller/crds/terraform.appvia.io_cloudresources.yaml
pkg/apis/terraform/v1alpha1/cloudresource_types.go
pkg/apis/terraform/v1alpha1/plan_types.go
pkg/cmd/tnctl/create/revision.go
pkg/controller/cloudresource/ensure.go
pkg/controller/cloudresource/metrics.go
pkg/controller/cloudresource/reconcile.go
pkg/controller/cloudresource/reconcile_test.go
pkg/controller/plan/ensure.go
pkg/controller/plan/reconcile_test.go
pkg/controller/revision/ensure.go
pkg/controller/revision/reconcile_test.go
pkg/handlers/cloudresources/mutation.go
pkg/handlers/cloudresources/mutation_test.go
pkg/handlers/cloudresources/validation_test.go
pkg/register/assets.go
pkg/utils/semvar_test.go
test/fixtures/revision.go

Currently a consumer would not be aware if a Cloud Resource has updates availabe, without checking the plan. In the pull request we have added a prometheus metrics for monitoring purposes which tracks if an updates is available as well as a status flag which is show on the kubectl get cloudresource, indicates an update is available

[FEATURE] - Cloud Resource Update Available

---

pkg/cmd/tnctl/get/generic.go
pkg/cmd/tnctl/get/get.go
pkg/cmd/tnctl/tnctl.go

This is largely just a convience command and it's annoying jumpiny between kubectl and tnctl. This feature simply calls the 'kubectl get' command for each of the resource types

[FEATURE] - CLI Get Command

---

pkg/controller/cloudresource/controller.go

Given the addition of the available update status, it's useful to reconcile on changes to the plan as it can keep the field in sync. This PR adds to the cloud resource controller the abilty to reconcile all cloud resource which reference a plan X, when plan X has a generational change

[FEATURE] - Cloud Resources Reconciles on Plan Changes

---

pkg/controller/configuration/ensure.go
pkg/controller/configuration/reconcile_test.go

The configuration controller was not setting the .status.resourceStatus correctly; which meant resources which were out of sync and waiting for a approval was not showing in the status (just the overall .status.condition). The logic was correctly i.e. it was still waiting for approval, just not indicating on the status

[BUGFIX] - Configuration Resource Status

---

pkg/cmd/tnctl/apply/apply.go
pkg/cmd/tnctl/delete/delete.go
pkg/cmd/tnctl/get/get.go
pkg/cmd/tnctl/tnctl.go

Adding some convenience aliases to kubectl apply and delete, just makes it easier not to switch between commands

[FEATURE] - Adding Convenience Aliases for Delete & Apply

---

pkg/cmd/tnctl/convert/configuration.go
pkg/cmd/tnctl/verify/revision.go

The current implmentation is using namespace match to generate the checkov policy - it makes more sense to test the revision against all possible policies in the cluster; plus has the benefit on not relying on the need to speak to a cluster when checking

[BUGFIX] - Generating Checkov Policy Per Constraint

---

pkg/cmd/tnctl/verify/revision.go
pkg/utils/slices.go
pkg/utils/slices_test.go

Ignoring the verification if the module spec has a local directory

[FEATURE] - Ignore Local Directories on Module Policy Verification

---

pkg/handlers/revisions/validation.go
pkg/handlers/revisions/validation_test.go

We should only enable the update protection if there is an update to the spec, changes to annotations and labels if fine

[BUGFIX] - Bypass Update Protection on Revision

---

pkg/apis/terraform/v1alpha1/revision_types.go

Ensuring we copy the cloud resource secret reference if defined

[BUGFIX] - CloudResource Secret Reference

---

pkg/cmd/tnctl/convert/revision.go
pkg/cmd/tnctl/verify/revision.go

Updating the output just to use double quotes around the names

[CLI] - Revision Verification

---

test/e2e/check-suite.sh

Using the Github run number instead of the run id as it's easier to match the fail to the logs

[E2E] - Diagnostic Bucket

---

test/e2e/integration/error-handler.bats

Occasionally it can take longer to acquire the pod name, adding a retry loop

[E2E] - Pod Name Retry

---

examples/revision.yaml
pkg/apis/terraform/v1alpha1/revision_types.go

Updating the 'tnctl create cloudresource' to also include required fields in the render

[CLI] - Create Cloud Resource CLI

---

charts/terranetes-controller/templates/deployment.yaml
charts/terranetes-controller/templates/serviceaccount.yaml
charts/terranetes-controller/values.yaml
cmd/controller/main.go
pkg/controller/configuration/controller.go
pkg/controller/configuration/delete.go
pkg/controller/configuration/ensure.go
pkg/server/server.go
pkg/server/types.go
pkg/utils/jobs/jobs.go
pkg/utils/slices.go
pkg/utils/slices_test.go

Adding the ability to add additional labels on the pods which run the terraform

[FEATURE] - Adding Custom Labels

---

cmd/source/source.go
cmd/source/source_test.go
go.mod
pkg/assets/job.yaml.tpl
pkg/controller/configuration/reconcile_test.go

Hello there 👋 
While evaluating terranetes I noticed it wasn't possible to use HTTP basic auth for downloading modules. Terraform/go-getter allows HTTP auth using the [`.netrc` file](https://developer.hashicorp.com/terraform/language/modules/sources#http-urls).
In this PR I used `HTTP_USERNAME` and `HTTP_PASSWORD` envs to write a `.netrc` file right before downloading the source. This file is written by default to the $HOME dir and I also had to change the job template to configure the same $HOME on all containers. This allows Terraform init/plan/apply to share the auth credentials, which is required when the source module includes instances to other private modules.

Add support for HTTP auth

---

charts/terranetes-controller/values.yaml
pkg/controller/configuration/ensure.go
pkg/controller/configuration/reconcile_test.go
test/e2e/integration/checkov.bats

The documentation was incorrect, there was probably the intent to add this but my fish brain forgot to raise the pull request. 
```yaml
kind: Policy
metadata:
name: default-authentication
spec:
defaults:
modules:
- github.com/appvia/terraform-aws-myprivaterepo:.*
namespace:
matchExpressions:
- key: kubernetes.io/metadata.name
operator: Exists
secrets:
- auth_key
```
The above as referenced in the documentation will inject based on labels selectors of the Configurations namespace. The code however was never implemented; only module selectors were added. 
https://terranetes.appvia.io/terranetes-controller/admin/defaults/#secrets

[BUG] - Namespace Selectory for Secrets

---

charts/terranetes-controller/templates/ca.yaml
charts/terranetes-controller/templates/deployment.yaml
charts/terranetes-controller/values.yaml

This PR updates the helm chart allowing a custom CA secret to be used with the terranetes-controller. This is useful when we don't want the Helm chart to manage the CA secret and instead have it managed by external tools.

Allow custom CA secret name in Helm chart

---

cmd/controller/main.go
pkg/server/types.go
pkg/server/webhooks.go

Currently, webhook configurations are named `validating-webhook-configuration` and `mutating-webhook-configuration`. Since webhooks are global resources these names can easily conflict with webhooks for other controllers installed on the cluster.
This PR adds the option of using the `terranetes-controller-` prefix when creating those webhooks. Since this can be a breaking change for existing installations of Terranetes I added it under a controller flag with the default being to use the unprefixed names.

Prefix webhook names with controller name

---

charts/terranetes-controller/templates/deployment.yaml
charts/terranetes-controller/values.yaml

This is a follow-up to https://github.com/appvia/terranetes-controller/pull/1263 exposing the webhook prefix configuration on the Helm chart.

Expose webhook prefix config on helm chart

---

pkg/controller/configuration/reconcile.go

The custom backend was not being picked up in the destroy phase; this was being caused due to the order of the ensure funcs. The provider would have been nil going into the ensureCustomBackendTemplate() and thus fallen into the default backend, which is kubernetes

[FIX] - Provider Backend

---

charts/terranetes-controller/templates/deployment.yaml
charts/terranetes-controller/values.yaml

This PR adds the `.Values.controller.extraArgs` values to the Helm chart. The idea is to use it for flags that aren't required and do not warrant a dedicated Values entry due to not being common enough. Also, this might simplify the release process when adding new args making them available without requiring a Helm chart release.

Add helm chart values for extra controller arguments

---

pkg/controller/ensure.go
pkg/controller/ensure_test.go

While rolling out Terranetes I noticed that on some of our clusters (the ones with a larger number of Configuration resources) terranetes was continuously reconciling all resources even when there were no changes. The `drift` controller was causing this and there was a significant increase in the CPU usage for the terranetes-controller pod. This can be seen on this graph for the workqueue add rate:
Upon further investigation, I noticed this was caused by the drift controller continuously updating the timestamp at `Configuration.Status.LastReconcile.Time`. The reason the issue only manifested on some clusters was due to how long the drift reconciler takes to run.
Since the `Configuration.Status.LastReconcile.Time` field is serialized with seconds resolution (e.g. "2024-03-04T14:00:19Z") if …

Only update last reconcile status when there are resource changes

---

pkg/controller/configuration/delete.go

I noticed `destroy` Jobs weren't including the configuration labels. Those labels are already present on `plan` and `apply` Jobs, having them also on `destroy` shouldn't cause any harm and makes kubectl querying easier.

Add configuration labels to destroy jobs

---

pkg/controller/cloudresource/ensure.go
pkg/controller/cloudresource/reconcile_test.go

Currently the authentication was not being copied over to the configuration resource. Update the code to default to Revision, and only if the CloudResource is set, allow it to override

[BUGFIX] - Authentication From Revision

---

pkg/controller/configuration/controller.go

Adding logging to the eviction of namespaces from the cache

[FEATURE] - Adding Evition Logging

---

pkg/controller/configuration/controller.go
pkg/controller/configuration/ensure.go
pkg/controller/configuration/helper.go

Its probably something silly, but after much trying to replicate the issue, i’m can’t see how the cache could not contain the namespace. The fact it appears to happen ever 11 hours is probably related to the cache expiration https://github.com/appvia/terranetes-controller/pull/1350/files#diff-53a4e552527dc2eab7835e6b4fdff466da76827aa2e7fa940c6b6c107d281bcbL177 … I’ve implemented in the change a fallback to to an direct api call, if the item is not in the cache. Perhaps long term it’s easier to just go with that and avoid any of the issues with caching at all ..

[BUGFIX] - Namespace Cache

---

charts/terranetes-controller/templates/backend.yaml

Trying to use a multi line string to set the terraform backend config results in a parsing error. The helm template needs to up updated to set the indent manually so that multi line string from the values.yaml has the correct indentation.
```
YAML parse error on terranetes-controller/templates/backend.yaml: error converting YAML to JSON: yaml: line 9: could not find expected ':'
```

Ensure custom backend templates have the correct indent

---

.golangci.yml

The skip-dirs has been deprecated and replaced with exclude-dirs

[BUILD] - Golang Lint Skipped Directories

---

charts/terranetes-controller/Chart.yaml
charts/terranetes-controller/templates/deployment.yaml
charts/terranetes-controller/values.yaml

Adding the 'configurations-threshold' value to the helm chart to enabling adding rate limiting

[FEATURE] - HELM Value for Configuration Rate Limiting

---

test/e2e/integration/apply.bats
test/e2e/integration/checkov.bats
test/e2e/integration/cloud/aws/costs.bats
test/e2e/integration/contexts.bats
test/e2e/integration/custom-state-backend.bats
test/e2e/integration/drift.bats
test/e2e/integration/infracost.bats
test/e2e/integration/plan.bats
test/e2e/integration/private.bats
test/e2e/integration/provider-state-backend.bats
test/e2e/integration/setup.bats

The status conditions on later versions of kubernetes has changed

[E2E] - Job Status

---

pkg/assets/job.yaml.tpl
pkg/utils/jobs/jobs.go
pkg/utils/jobs/jobs_test.go

This was missing from #1484 so the bound tfvars were not consumable.

Ensure TFVars file included in volume mount when creating job

---

charts/terranetes-controller/values.yaml
test/e2e/integration/setup.bats

Moving over to the helm managed webhooks by default and will deprecate the legacy ones

[FEATURE] - Switching Helm Webhooks

---

charts/terranetes-controller/templates/webhooks.yaml

We have a duplicate name in the webhook, when namespace protection is enabled

[FIX] - Webhook Name

---

charts/terranetes-controller/Chart.yaml
charts/terranetes-controller/values.yaml

Previously the webhooks were managed by the controller itself; we've move this to being managaed as part of the helm deployment itself now

[HELM] - Switching to Helm Webhooks

---

pkg/cmd/tnctl/create/revision.go
pkg/cmd/tnctl/verify/revision.go

Update the links to the checkov documentation (easier to use homepage for now) and adding guileline, i.e. hyperlinks for the fixes
```
🔰 Validating against Checkov Security Policy
▫️ Checkov is using the code, not the plan, consider --use-terraform-plan  🟠
▫️ Found 1 security policies to validate against                           🟢
▫️ Revision has passed 0 checks in policy: "checkov"                       🟢
▫️ Check ID against documentation at https://www.checkov.io                🟢
▫️ Ensure Terraform module sources use a commit hash                       🔴
Check ID: CKV_TF_1                                                   
Resource: module.main.vpc                                            
Guideline: https://docs.prismacloud.io/en/enterprise-edition/policy-reference/supply-chain-poli …
```

[FEATURE] - Verify Revision

---

cmd/step/main.go
cmd/step/types.go

This adds flags to allow for commands to be retried with backoff (at this time all commands) but simple.
Regression test
```
13:44 $ docker run -it --entrypoint /bin/step europe-west2-docker.pkg.dev/appvia-hub/terranetes-executor-step-up/wf-step:1.0.4 --comment=gogo --command=true
=======================================================
GOGO
=======================================================
INFO[0000] successfully executed the step
✔ ~/projects/appvia/terranetes-controller [add-retry-to-step|✚ 2]
13:44 $ docker run -it --entrypoint /bin/step europe-west2-docker.pkg.dev/appvia-hub/terranetes-executor-step-up/wf-step:1.0.4 --comment=gogo --command=false
=======================================================
GOGO
=======================================================
ERRO[0000] …
```

add a rety option to the step command

---

cmd/step/main.go

The wait was waiting on the **wrong** file - it would never fail even if the failure file existed

fail when there is a failure file

---

pkg/cmd/tnctl/create/revision.go
pkg/utils/download.go

Attempting to fix up the issue related to artifactory download in the tnctl create revision command,
We had a bug in the code which was cause issues with direct http calls.
```go
-       if strings.HasPrefix(source, "http") {
-               source = strings.TrimPrefix(source, "http://")
-               source = strings.TrimPrefix(source, "https://")
```
This has been removed.
The main issue however was found when dealing with Artifactory assets, using the follow example.
```shell
bin/tnctl create revision https://USERNAME:TOKEN@trial4x3ad1.jfrog.io/artifactory/art-terraform-modules-local/kash/rds/aws/1.0.0 -f test.yaml
```
We are getting a 404. Adding a `.zip` to the URL i.e. `/kash/rds/aws/1.0.0.zip` allowed us to download the zip file. I’m guessing we are missing a headers information …

[FIX] - Terrenetes Download

---

pkg/utils/policies/find.go

When applying a Policy with 
`spec.constraints.checkov.selector.resource.matchExpressions`  
or 
`spec.constraints.checkov.selector.resource.matchLabels`
the filters are totally ignored, while with namespace selector the filters properly work.

error in applying checkov resource selector

---

charts/terranetes-controller/templates/deployment.yaml
charts/terranetes-controller/templates/rbac.yaml

When setting the parameter to false, the CRDs are still being registered and controller fails to start as it is not able to read the CRDs.

[HELM] fix the registerCRDs parameter

---

.github/workflows/ci.yaml

Changed the run-on from ubuntu-20.04 (deprecated) to latest

[BUILD] - Helm Job Image Version

---

.github/workflows/e2e.yaml

Potential fix for [https://github.com/appvia/terranetes-controller/security/code-scanning/21](https://github.com/appvia/terranetes-controller/security/code-scanning/21)
To fix the issue, add a `permissions` block at the root level of the workflow. This block will apply to all jobs in the workflow unless overridden by job-specific `permissions` blocks. Based on the workflow's actions, the minimal required permissions are likely `contents: read` (to access repository contents) and possibly `packages: write` (to upload artifacts). The `permissions` block should be added near the top of the file, just after the `name` and `run-name` fields.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 21: Workflow does not contain permissions

---

.github/workflows/versions.yaml

Potential fix for [https://github.com/appvia/terranetes-controller/security/code-scanning/20](https://github.com/appvia/terranetes-controller/security/code-scanning/20)
To fix the issue, we will add a `permissions` block at the workflow level to explicitly define the required permissions. Based on the workflow's actions, the following permissions are needed:
- `contents: read` for accessing repository contents.
- `pull-requests: write` for creating pull requests.
This ensures that the workflow has only the necessary permissions to perform its tasks.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 20: Workflow does not contain permissions
