appvia/terranetes-controller

- .github/workflows/latest.yaml
Fixing up the workflow for master
> [CI] Latest Workflow

- charts/templates/deployment.yaml
- charts/values.yaml
- cmd/controller/main.go
- docs/template.md
- pkg/apis/terraform/v1alpha1/configuration_types.go
- pkg/controller/configuration/controller.go
- pkg/controller/configuration/delete.go
- pkg/controller/configuration/ensure.go
- pkg/controller/configuration/reconcile.go
- pkg/controller/configuration/reconcile_test.go
- pkg/server/server.go
- pkg/server/types.go
- pkg/utils/jobs/jobs.go
- test/fixtures/template.go
Adding the ability to override the job template
> [FEATURE] - Custom Job Override

- charts/templates/ca.yaml
Fixing a bug in the helm chart around the certficate generated for the webhooks
> [BUGFIX] - Autogenerate Certificate

- docs/executor.md
Adding some docs on the executor image
> [DOCS] - Executor Docs

- charts/values.yaml
Bumping the versioFix versionn of the helm chart to v0.1.0 ready to release
> Bumping the Version

- .github/workflows/release.yaml
Adding a kind install into the ci build for the e2e to work
> [CI] - Kind Installation

- .github/workflows/release.yaml
- test/e2e/check-suite.sh
- test/e2e/integration/apply.bats
- test/e2e/integration/confirm.bats
- test/e2e/integration/destroy.bats
- test/e2e/integration/plan.bats
- test/e2e/integration/provider.bats
- test/e2e/integration/setup.bats
Fixing up the typo on the github workflow for releasing
> [CI] - Fixing Github Workflow (Release)

- .github/workflows/latest.yaml
- docs/development.md
- test/e2e/check-suite.sh
- test/e2e/integration/confirm.bats
- test/e2e/integration/destroy.bats
- test/e2e/integration/plan.bats
Expanding on development readme; local development, components, unit test and so forth
> [DOCS] - Development Readme

- .github/workflows/release.yaml
We forgot to add the docker login
> [CI] - Fixing the Release Step

- README.md
Updating the readme to have a direct link to the documentation page
> [DOCS] Updating the README

- .github/workflows/e2e.yaml
- .github/workflows/release.yaml
Moving the E2E workflow into another file and reusing for release. This makes it easier to manually trigger the workflow I hope
> [CI] - E2E Workflow

- LICENSE
Adding a license to the project
> [DOCS] - Adding License File

- .github/workflows/ci.yaml
Adding a dependency review to the ci workflow
> [CI] - Dependency Review

- pkg/controller/configuration/controller.go
- pkg/controller/configuration/delete.go
- pkg/controller/configuration/ensure.go
- pkg/controller/configuration/reconcile_test.go
- pkg/controller/ensure.go
- pkg/controller/provider/controller.go
- pkg/controller/provider/ensure.go
- pkg/controller/status.go
- test/events.go
The current implementation does not record an event on crucial failure such as action required. These would be useful
to trigger notifications. The PR add a recorder and now by default raises an event on all action required conditions
> [FEATURE] - Kubernetes Events

- .github/workflows/ci.yaml
Only running the dependency check on a pull request
> [CI] - Dependency Check

- charts/values.yaml
Bumping the version of the helm chart for next release
> [RELEASE] - Version v0.1.2

- .github/workflows/release.yaml
Trying to reuse the E2E workflow instead of duplicating it
> [CI] - Reuse E2E Workflow

- README.md
Just fixing up the readme links
> [DOCS] - Fixing the README links

- pkg/assets/job.yaml.tpl
Removing the need for a resoruce lock on the terraform state
> [FEATURE] - Resource Lock

- .github/workflows/ci.yaml
- .github/workflows/e2e.yaml
Trying to speed up the execution time of the images by breaking them up
> [CI] - Workflow Speed

- .github/workflows/ci.yaml
- .github/workflows/e2e.yaml
- charts/Chart.yaml
Adding additional metadata to the chart
> [HELM] - Chart Metadata

- .github/workflows/ci.yaml
- .github/workflows/e2e.yaml
- Makefile
The build wasn't correctly passing in the LFLAGS and version into the compiled binaries
> [BUILD] - Makefile Fix

- .github/workflows/release.yaml
- test/e2e/integration/cloud/azure/destroy.bats
- test/e2e/integration/cloud/azure/plan.bats
- test/e2e/integration/destroy.bats
Fixing up the reference to the branch in the azure plan
> [E2E] - Fixing the reference in E2E

- charts/terraform-controller/Chart.yaml
- charts/terraform-controller/values.yaml
Adding a 'v' to the version semvar
> [HELM] - Completing the Version

- .github/dependabot.yml
Adding a dependabot configuration
> [BUILD] - Adding Dependabot Config

- charts/terraform-controller/Chart.yaml
- charts/terraform-controller/values.yaml
- indenting the yaml correctly and adding a few comments.
Mainly using this to trigger a deployment
> [HELM] - Minior Changes

- charts/terraform-controller/Chart.yaml
- go.mod
- go.sum
- pkg/controller/configuration/ensure.go
- pkg/controller/configuration/metrics.go
- test/e2e/check-suite.sh
- test/e2e/integration/costs.bats
- test/e2e/integration/setup.bats
- vendor/github.com/prometheus/client_golang/prometheus/collectors/collectors.go
- vendor/github.com/prometheus/client_golang/prometheus/collectors/go_collector_go116.go
- vendor/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest.go
- vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
- vendor/github.com/prometheus/client_golang/prometheus/go_collector_go116.go
- vendor/github.com/prometheus/client_golang/prometheus/go_collector_latest.go
- vendor/github.com/prometheus/client_golang/prometheus/internal/go_runtime_metrics.go
- vendor/modules.txt
Adding the cost of the configuration into the prometheus metrics
> [FEATURE] - Record Configuration Cost Metrics

- Makefile
- charts/terraform-controller/Chart.yaml
- charts/terraform-controller/values.yaml
Bumping the application version in the helm chart
> [HELM] - Bumping Application Version

- charts/terraform-controller/Chart.yaml
Bumping the chart version to v0.2.3
> [HELM] - Bumping Version of Chart

- .github/dependabot.yml
Changing the target branch for dependabot to raise pull requests against
> [BUILD] - Dependabot Target Branch

- README.md
This feature can be dropped from the roadmap as its already done and merged
> [DOCS] - Readme Change

- pkg/controller/configuration/ensure.go
- pkg/controller/configuration/reconcile.go
Fixing a typo on the method name
> [BUGFIX] - Fixing Method Name Typo

- pkg/controller/status.go
- pkg/controller/status_test.go
Currently we are only raising the conditions on the configuration status, it would be helpful from a debugging point of view to raise in the logs as well
> [LOGGING] - Condition Logging

- pkg/utils/templates_test.go
Removing the method no longer in use and adding some unit tests
> [CLEAN] - Template Unit Tests

- pkg/apiserver/handlers.go
- pkg/utils/kubernetes/pods.go
- pkg/utils/kubernetes/pods_test.go
Moving the utility method into a common package
> [GENERAL] - Moving Utility Method into common

- test/e2e/check-suite.sh
- test/e2e/integration/apply.bats
- test/e2e/integration/cloud/aws/plan.bats
- test/e2e/integration/drift.bats
Adding a E2E to verify the drift detection is working correctly
> [E2E] - Drift Detection E2E

- docs/development.md
The development docs were a little out of date. This PR just brings them up to date.
> [DOCS] - Development Docs

- charts/terraform-controller/Chart.yaml
- charts/terraform-controller/values.yaml
Releasing the helm chart updates for the v0.2.0 release
> [HELM] - Helm Release for v0.2.0

- pkg/controller/configuration/ensure.go
- pkg/controller/configuration/reconcile_test.go
- test/fixtures/state.go
Cleaning up the unit tests and grouping related checks together. Also adding a check to the costs integration
> [TESTS] - Configuration Controller Unit Tests

- pkg/server/server.go
Tiny one, just adding the version to the display log
> [LOGGING] - Display the version

- pkg/assets/job.yaml.tpl
- pkg/controller/configuration/reconcile_test.go
Currently the checkov results while bring enforced were not being shown in the pod output, making it diffcult to debug
> [BUGFIX] - Checkov Results

- charts/terraform-controller/Chart.yaml
- charts/terraform-controller/values.yaml
Releases the chart updates for the v0.2.2 release
> [HELM] - Release Helm Chart v0.2.2

- charts/terraform-controller/Chart.yaml
- charts/terraform-controller/values.yaml
Releasing the updates for the helm chart
> [HELM] - Chart Version v0.2.3

- cmd/source/source.go
Fixing a bug in the source binary which was correctly handling the query parameter
> [BUGFIX] - Private Repositories & SSH Key

- test/e2e/check-suite.sh
- test/e2e/integration/cloud/aws/costs.bats
Currently we are using a bucket for our E2E which generates no costs so we allowed for a error to keep through with the infracost integration, this was fixed, but going forward we need checks to ensure it's not broken again
- added a costs checks to the aws stack, this creates a configuration which generates actual costs so we can check against
> [E2E] Infracost E2E

- charts/terraform-controller/Chart.yaml
- charts/terraform-controller/values.yaml
Bumping the versions in the helm chart to match the new release
> [HELM] - Release v0.2.4

- charts/terraform-controller/values.yaml
- cmd/controller/main.go
Bumping the version of the infracost we choose from 0.9.3 to 0.10.3
> [BUILD] - Bumping the Infracost Version to v0.10.3

- charts/terraform-controller/Chart.yaml
- charts/terraform-controller/values.yaml
Bumping the versions in the helm chart
> [HELM] - Release for v0.2.5

- charts/terraform-controller/Chart.yaml
Bumping the version of the chart to push a release
> [HELM] - CHart Version v0.2.12

- test/e2e/check-suite.sh
- test/e2e/integration/checkov.bats
- test/e2e/integration/cloud/aws/destroy.bats
- test/e2e/integration/cloud/aws/infracost.bats
- test/e2e/integration/cloud/aws/plan.bats
- test/e2e/integration/costs.bats
- test/e2e/integration/destroy.bats
- test/e2e/integration/infracost.bats
-  cleaned up some checks
-  improved the integration checks for infracost
-  added integration checks for checkov
> [E2E] - Improvements to E2E

- charts/terraform-controller/values.yaml
- cmd/controller/main.go
- test/e2e/integration/cloud/aws/infracost.bats
Switched all the images to use latest by default and bumped the version of checkov (i.e. known working version) to 2.0.1211
> [IMAGES] - Image Versions

- .github/workflows/ci.yaml
We only need to perform the chart increment on master branch
> [CI] - Helm Chart Linting

- pkg/cmd/tnctl/workflow/assets/github/main.yaml.tpl
Dropping the readme check for now
> [BUGFIX] - Dropping the Readme Check

- .github/workflows/ci.yaml
- pkg/cmd/tnctl/workflow/assets/github/ci.yaml.tpl
> [BUGFIX] - Fixing Workflow

- pkg/cmd/tnctl/workflow/assets/github/ci.yaml.tpl
- pkg/cmd/tnctl/workflow/assets/github/main.yaml.tpl
Adding the workflow id back on the stage
> [BUGFIX] - Adding the Workflow ID

- pkg/cmd/tnctl/workflow/assets/github/main.yaml.tpl
We only need to run the checkout on pull requests
> [BUGFIX] - Costs on Pull Requests

- pkg/cmd/search/github/github.go
You need to know if your calling a org or user and in order to list private repos
> [CLI] - Github Repository Listing

- pkg/cmd/search/github/github.go
- pkg/cmd/search/terraform/registry.go
- pkg/cmd/search/types.go
- pkg/cmd/tnctl/search/search.go
Fixing up github to always use github instead and using a wrap in the description
> [FEATURE] - Terranetes Search CLI

- Makefile
The version and gitsha was not correctly being pasted to the binaries
> [BUILD] - Fixing LFAGS

- .github/workflows/latest.yaml
- .github/workflows/release.yaml
- Makefile
Upating the release workflow to include the building of the CLI and creating a Github release
> [BUILD] - Release Workflow

- pkg/cmd/tnctl/workflow/create.go
Adding the ability to override the template URL from the configuration file
> [CLI] - Workflow Override

- pkg/cmd/tnctl/build/build.go
Prompting the user for a secret name if the module has outputs
> [CLI] - Build Command

- pkg/cmd/tnctl/describe/assets/describe.yaml.tpl
- pkg/cmd/tnctl/describe/describe.go
Fixing up some minor issues in the describe command
> [CLI] - Describe Command

- pkg/apis/terraform/v1alpha1/configuration_types.go
- pkg/controller/configuration/ensure.go
- pkg/controller/configuration/reconcile_test.go
- pkg/handlers/configurations/validation.go
- pkg/handlers/configurations/validation_test.go
Currently the outputs from the modules are written using the same name as the terraform output. There may be occasion though when being able to rewrite the key is useful for the workload secrets. With this PR we've added the ability to use the form KEY:NEWNAME i.e. database_endpoint:mysql_host which remaps the key in the secret
```yaml
---
kind: Configuration
metadata:
name: bucket
spec:
module: https://github.com/terraform-aws-modules/terraform-aws-rds.git?ref=v3.1.0
providerRef:
name: aws
writeConnectionSecretToRef:
name: test
keys:
- database_endpoint:mysql_host
```
> [FEATURE] - Secret Renaming

- charts/terraform-controller/Chart.yaml
Bumping the version in the Chart.yaml to reference the latest version
> [HELM] - Helm Release (v0.2.7)

- .github/workflows/release.yaml
Fixing the release workflow i.e. file -> files argument
> [CI] - Release Workflow Fix

- charts/terraform-controller/Chart.yaml
- charts/terraform-controller/values.yaml
Need to move those versions into a template before it happens again
> [HELM] - Fixing Application Bump

- pkg/cmd/tnctl/search/search.go
Currently we default to the module name for the resource name, we should instead keep the default but allow the user to override on flag or prompt
> [CLI] - Build Command Resource Name

- charts/terraform-controller/values.yaml
Bumping the version to v0.10.7 from v0.10.3
> [HELM] - Infracost Image Update

- .github/workflows/develop.yaml
- .github/workflows/latest.yaml
Just changing the workflow step names
> [CI] - Workflow Names

- charts/terraform-controller/values.yaml
Bumping the default version of checkov to use
> [HELM] - Bumping Version Checkov 2.1.67

- charts/terraform-controller/values.yaml
Bumping the default version of infracost to v0.10.8
> [HELM] - Bumping Infracost Version 0.10.7, 0.10.8

- charts/terraform-controller/values.yaml
Bumping the default version of terraform image from v1.1.9 to v1.2.5
> [HELM] - Terraform Version v1.2.5

- pkg/apis/terraform/v1alpha1/configuration_types.go
Updating the resource status for deletion from OutOfSync to Deleting to
make things more clear.
> [BUGFIX] - Resource Status when deleting

- pkg/apiserver/handlers.go
Highlighted by the CodeQL analysis, we should be ensuring the user input
before passing through; very least this could be used to DDOS the
logging.
> [BUGFIX] - Sanity Checking Query Parameters

- pkg/apis/terraform/v1alpha1/configuration_types.go
- pkg/assets/job.yaml.tpl
- pkg/controller/configuration/detect_errors.go
- pkg/controller/configuration/ensure.go
- pkg/utils/jobs/jobs.go
- pkg/utils/terraform/errors.go
- pkg/utils/terraform/errors_test.go
- added some testing errors detectors and tests
- added the error detection ensure method to the configuration controller
- fixed a small typo verion -> version
- added a constant for the name of the terraform container
- fixed up the unit tests
> [FEATURE] - Detection of Errors

- charts/terraform-controller/Chart.yaml
- charts/terraform-controller/values.yaml
Bumping the release version to v0.2.9
> [HELM] - Release v0.2.9

- .github/workflows/release.yaml
Fixed a typo which was made on the release workflow
> [CI] - Github Release Workflow

- .github/workflows/codeql.yml
Adding the ability to trigger the codeql workflow
> [CI] - Adding Workflow Dispatch - CodeQL

- README.md
> [DOCS] - CodeQL Badge

- charts/terranetes-controller/Chart.yaml
Bumping the version of the helm chart
> [HELM] - Bumping the Helm Chart

- .github/workflows/e2e.yaml
Renaming things is always a pain - fixing up what i hope is the last reference to the old name
> [CI] - Fixing Naming on Docker Images

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Releasing the v0.3.0 application release
> [HELM] - Release v0.3.0 Chart

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Adding the changes to the helm chart for the release
> [HELM] - Helm Release for v0.3.1

- cmd/controller/main.go
Updating the version string returns to include the tag and gitsha
> [FEATURE] - Updating Controller Version String

- .github/workflows/e2e.yaml
- test/e2e/check-suite.sh
- test/e2e/integration/setup.bats
Adding the ability to install from the official chart to ensure functionality
> [E2E] - Install Official Chart

- .github/workflows/e2e.yaml
> [E2E] - Use Chart Option

- .github/workflows/e2e.yaml
- test/e2e/check-suite.sh
Fixing up the check suite script
> [E2E] - Check Suite Script

- pkg/cmd/tnctl/config/sources_list.go
- pkg/cmd/tnctl/config/sources_test.go
Updating the sources command to check the configuration does not exist error
> [TESTS] - Update CLI Tests for Sources Command

- pkg/cmd/tnctl/kubectl/kubectl.go
- pkg/cmd/tnctl/kubectl/kubectl_test.go
- pkg/cmd/tnctl/kubectl/plugin.go
- pkg/cmd/tnctl/kubectl/plugin_test.go
- pkg/cmd/tnctl/kubectl/suite_test.go
- pkg/cmd/tnctl/tnctl.go
Adding the kubectl plugin command used to generate the script shortcuts
> [CLI] - Kubectl Plugin Command

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
> [HELM] - Release v0.3.2

- cmd/tnctl/main.go
- pkg/cmd/config.go
- pkg/cmd/factory.go
- pkg/cmd/factory_test.go
- pkg/cmd/helper.go
- pkg/cmd/option.go
- pkg/cmd/tnctl/config/sources_list.go
- pkg/cmd/tnctl/config/sources_test.go
- pkg/cmd/tnctl/config/view.go
- pkg/cmd/tnctl/config/view_test.go
- pkg/cmd/tnctl/kubectl/kubectl_test.go
- pkg/cmd/tnctl/kubectl/plugin_test.go
- pkg/cmd/tnctl/tnctl_test.go
- pkg/cmd/types.go
Providing a easy means to make the configuration exchangable
> [FEATURE] - Adding Configuration Interface

- pkg/cmd/factory.go
- pkg/cmd/factory_test.go
- pkg/cmd/tnctl/approve/approve_test.go
- pkg/utils/kubernetes/clients.go
Moving the kubernetes clients methods into the package rather than the factory
> [CLEAN] - Kubernetes Clients

- docs/development.md
Updating the E2E requirements and docs as it's slightly changed since we last added this.
> [DOCS] - Updating Development Docs

- pkg/cmd/tnctl/kubectl/kubectl.go
- pkg/cmd/tnctl/kubectl/plugin.go
Adding some CLI docs and examples to the kubectl command in tnctl
> [CLI] - Adding Docs to Kubectl Command

- .github/workflows/ci.yaml
Adding additionals compilations jobs for the CLI and support binaries
> [CI] - Support Binaries & CLI

- Makefile
Adding a fix shortcuts into the Makefile to trigger off E2E on the development branch
> [CI] - Trigger Development E2E

- examples/provider-secrets.yaml
Adding some example secret so people get the idea quickly
> [DOCS] - Example Provider Secrets

- README.md
Updating the readme a little to include a why
> [DOCS] - Updating Readme

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the versions in the helm chart to release v0.3.4
> [HELM] - Release v0.3.4

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Theres no changes in the release to the controller, but for consistency with the CLI change i'll bump the version
> [HELM] - Release v0.3.5

- pkg/cmd/tnctl/convert/configuration.go
- pkg/cmd/tnctl/convert/configuration_test.go
- pkg/cmd/tnctl/convert/convert.go
- pkg/cmd/tnctl/convert/convert_test.go
- pkg/cmd/tnctl/tnctl.go
Adding the tnctl convert configuration command which is used to convert a Configuration
resource back to terraform code
> [FEATURE] - Convert Command CLI

- pkg/cmd/tnctl/convert/configuration.go
- pkg/cmd/tnctl/convert/configuration_test.go
We had a logic error in the way it was filtering the source module
> [BUGFIX] - Convert Configuration Source

- pkg/assets/assets_test.go
- pkg/cmd/tnctl/convert/configuration.go
- pkg/cmd/tnctl/describe/describe.go
- pkg/cmd/tnctl/kubectl/plugin.go
- pkg/controller/configuration/ensure.go
- pkg/utils/jobs/jobs.go
- pkg/utils/template/templates.go
- pkg/utils/template/templates_test.go
- pkg/utils/terraform/template.go
- pkg/utils/terraform/template_test.go
- pkg/utils/terraform/utils.go
Moving from dependencies around to reduce the impact of importing.
> [CLEANUP] - Dependencies

- README.md
Dropping the item from the roadmap
> [DOCS] - Readme Update

- charts/terranetes-controller/crds/terraform.appvia.io_policies.yaml
- pkg/apis/terraform/v1alpha1/constraint_types.go
- pkg/register/assets.go
Changing the name from the externalSource to source
> [BUGFIX] - Changing the Policy Source Field

- charts/terranetes-controller/values.yaml
Bumping the default version of the image used in the jobs
> [BUILD] - Infracost Version (v0.10.9 -> v0.10.10)

- pkg/cmd/tnctl/describe/describe.go
- pkg/cmd/tnctl/logs/logs.go
Adding a default namespace for logs and describe command
> [CLI] - Setting a Default Namespace

- examples/private_module_configuration.yaml
Adding an example for a private terraform module and ssh clone
> [DOCS] - Adding Private Module Example

- charts/terranetes-controller/values.yaml
Bumping the image version in the helm chart
> [BUILD] - Terraform Version (v1.2.5 - v1.2.7)

- charts/terranetes-controller/values.yaml
Bumping the version of the default image used in the jobs
> [BUILD] - Checkov Version (2.1.104 -> 2.1.137)

- pkg/apiserver/logging/metrics.go
Adding API Server metrics for all http requests
> [FEATURE] - Adding API Server Metrics

- .github/workflows/images.yaml
- Makefile
- images/Dockerfile.cli
Publishing a image for the terranetes CLI
> [BUILD] - Publishing an Image for CLI

- charts/terranetes-controller/crds/terraform.appvia.io_policies.yaml
- pkg/apis/terraform/v1alpha1/constraint_types.go
- pkg/assets/job.yaml.tpl
- pkg/controller/configuration/reconcile_test.go
- pkg/handlers/policies/validation.go
- pkg/handlers/policies/validation_test.go
- pkg/register/assets.go
- pkg/utils/jobs/jobs.go
Various fixes to the controller to support central checkov policy.
- update the job template to support the feature
- updated the policy handlers to correctly validate the policy
> [BUGFIX] - Central Security Policy

- pkg/assets/job.yaml.tpl
- pkg/controller/configuration/reconcile_test.go
- pkg/utils/jobs/jobs.go
Just cleaning the template up a little post changes to central policy
> [CLEAN] - Cleaning the Job Template

- .github/workflows/ci.yaml
- hack/install-trivy.sh
Added image scanning via trivy to the CI
> [CI] - Adding Image Scanning

- pkg/assets/job.yaml.tpl
- pkg/controller/configuration/reconcile_test.go
- pkg/utils/terraform/template_test.go
This is not required as we a checking against the actual plan which has already incorporated the variables
> [CLEAN] - Dropping Checkov Variables Options

- .github/workflows/versions.yaml
Adding a automation to keep track of image versions
> [CI] - Image Version Automation

- .github/workflows/e2e.yaml
- test/e2e/check-suite.sh
On failure we push some diagnostics for later review
> [E2E] - Adding Diagnostics to E2E

- pkg/assets/job.yaml.tpl
- pkg/controller/configuration/reconcile_test.go
- pkg/utils/jobs/jobs.go
- test/e2e/check-suite.sh
Accidently dropped the inclusive of the variables in a previous commit
- added an additional unit test to ensure we don't have the same mistake
> [BUGFIX] - Terraform Variables

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Adding the updates for the release
> [HELM] - Release Chart for v0.3.7

- pkg/controller/drift/ensure.go
- pkg/controller/drift/reconcile_test.go
We were calculating the drift threshold incorrectly by only summing those with the annotations.
Instead we should have been taking into account those current in-progress i.e running
> [BUGFIX] - Drift Threshold

- .github/workflows/versions.yaml
Fixing up the versions workflow when install in the yq command
> [CI] - Versions Workflow

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Updating the helm chart for release v0.3.8
> [HELM] - Chart Release v0.3.8

- .github/workflows/versions.yaml
Switching to the develop branch not master
> [CI] - Image Versions

- test/e2e/assets/terraform/google/main.tf
- test/e2e/assets/terraform/google/variables.tf
Adding the project id variable to the E2E google terraform manifests
> [E2E] - Adding Google Project ID

- .github/workflows/e2e.yaml
- .github/workflows/release.yaml
- Makefile
- docs/development.md
- test/e2e/integration/cloud/google/plan.bats
- test/e2e/integration/cloud/google/provider.bats
Adding Google to the E2E process
> [E2E] - Google E2E

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Added the changes for the v0.3.9 release
> [HELM] - Release for v0.3.9

- README.md
Changing the link to the main page
> [DOCS] - Updating the Readme

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
Forgot to add the google e2e as a dependency for the final release step
> [E2E] - Release Dependency Workflow

- pkg/assets/job.yaml.tpl
Currently additional secrets are only added the main terraform container - but to make it
useful we need to add to all of them. Else allow the user to pick and choose
> [BUGFIX] - Additional Secrets

- Makefile
Fixing the typo on the makefile comment
> [BUILD] - Fixing Typo on Makefile Comment

- pkg/cmd/tnctl/logs/logs.go
- pkg/cmd/tnctl/logs/logs_test.go
- pkg/utils/kubernetes/update_test.go
- test/fixtures/configurations.go
- test/fixtures/factory.go
The logs command was not correctly find the pods due to an logic error.
- added unit tests to the command
> [CLI] - Logs Command Fixes

- test/e2e/integration/error-handler.bats
Fixing a small typo in the bats test
> [E2E] - Fixing Namespace Creation in E2E

- .dockerignore
Adding a .dockerignore to ignore anything in the bin and release folders
> [BUILD] - Docker Ignore File

- Makefile
- charts/terranetes-controller/templates/rbac.yaml
Ensuring the legacy service account is still functional and bound to the local role.
> [HELM] - Ensure Legacy ServiceAccount

- pkg/controller/configuration/delete.go
Ensuring we raise a event on and log when the resource is deleted
> [FEATURE] - Deletion Event

- .github/workflows/ci.yaml
- .github/workflows/images.yaml
- .github/workflows/release.yaml
- charts/terranetes-controller/values.yaml
Bumping the version of the actions to v3 to remove the deprecation
warning.
> [BUILD] - Github Actions Upgrade

- Makefile
- pkg/cmd/tnctl/convert/configuration_test.go
- pkg/cmd/tnctl/logs/logs_test.go
Fixing up the unit tests for ignore vendor completely
> [TESTS] - Fixing Unit Test

- .github/workflows/images.yaml
Updating the cosign action to sigstore/cosign-installer@v2.8.1
> [CI] - Updating Cosign Action

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Added the chart changes for the v0.3.11 release
> [HELM] - Chart for v0.3.11 Releaase

- charts/terranetes-controller/Chart.yaml
The github release stage wasn't kicked off
> [HELM] - Chart Release Fix

- pkg/cmd/tnctl/describe/assets/describe.yaml.tpl
The policies were not being shown when the costs integration was disabled
> [CLI] - Checkov Policies on Describe

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Added the chart updates for the release
> [HELM] - Chart Updates for v0.3.12

- .github/workflows/e2e.yaml
Related to a bug https://github.com/actions/upload-artifact/issues/270
> [BUILD] - Pegging the Artifact Upload to @v2.2.4

- .github/workflows/e2e.yaml
The upgrade of the artifact upload is still throwing issues
> [BUILD] - Action Throw Upload Errors

- pkg/controller/configuration/ensure.go
- pkg/controller/status.go
An extra line here and ensure the log is using the fields logger
> [BUILD] - Minor Code Changes

- images/Dockerfile.cli
- images/Dockerfile.controller
- images/Dockerfile.executor
Updating the bases images to use Alpine v3.17
> [IMAGES] - Alpine Base Image

- pkg/cmd/tnctl/logs/logs.go
Currently when looking for the logs of a build we only try once. In mostsituations this is sufficient but occasionally the controller can take longer to kick off the build. This pull requests adds retry logic to give's some more time.
> [FEATURE] - Retry Logic for Pod Logs

- .golangci.yml
- Makefile
- cmd/source/source.go
- cmd/step/main.go
- pkg/apis/terraform/v1alpha1/configuration_types.go
- pkg/cmd/config.go
- pkg/cmd/search/github/github.go
- pkg/cmd/search/terraform/registry.go
- pkg/cmd/tnctl/build/build.go
- pkg/cmd/tnctl/describe/describe.go
- pkg/cmd/tnctl/kubectl/plugin.go
- pkg/cmd/tnctl/search/search.go
- pkg/cmd/tnctl/state/clean.go
- pkg/cmd/tnctl/state/state.go
- pkg/cmd/tnctl/workflow/create.go
- pkg/controller/configuration/delete.go
- pkg/controller/configuration/ensure.go
- pkg/controller/drift/ensure.go
- pkg/controller/ensure.go
- pkg/handlers/configurations/validation.go
- pkg/handlers/policies/validation.go
- pkg/server/server.go
- pkg/server/webhooks.go
- pkg/utils/download.go
- pkg/utils/kubernetes/clients.go
- pkg/utils/random.go
Enabled more linters from golangci and fixed up the various issues found
> [BUILD] - Enabled More Linters

- images/assets/watch_logs.sh
- test/e2e/check-suite.sh
On E2E this is causing an occasion issue as it's taking too long to pull the images
> [E2E] - Bumping Log Watch Retries

- pkg/cmd/helper.go
- pkg/cmd/tnctl/search/search.go
Currently the providers are supplied or hardcoded - it would be nice to lookup the providers configured in the current kube context
> [FEATURE] - Lookup Providers in cluster for CLI Search

- Makefile
Adding a stage to the Makefile to retrieve the diagnostics from the bucket post E2E failures
> [BUILD] - Adding Diagnostics Makefile Stage

- .github/workflows/e2e.yaml
Removing the version pinning of the kind kubernetes version and installing latest
> [E2E] - Cluster Version of Kind

- pkg/apis/terraform/v1alpha1/provider_types.go
- pkg/controller/provider/ensure.go
- pkg/controller/provider/reconcile_test.go
Checking the provider secret for validation issues - also ignore unkown providers
> [FEATURE] - Provider Secret Validation

- Makefile
Adding a diagnostics Makefile target to remove all the files
> [BUILD] - Diagnositics Cleanup Target (Makefile)

- .github/workflows/versions.yaml
- charts/terranetes-controller/values.yaml
- test/e2e/integration/drift.bats
Using the CI image which is 98Mb vs the full image at 500Mb - also adding an update to the workflow
> [IMAGE] - Changing to CI Infracost Image

- .github/workflows/e2e.yaml
Github workflow support dynamic run names https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name
> [E2E] - Adding Run Name to Workflow

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the versions in the chart
> [HELM] - Release v0.3.14

- pkg/apis/terraform/v1alpha1/configuration_types.go
Adding a utility method to add a key to the write secrets
> [BUILD] - Adding AddKey() Method to Configuration Secrets

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the versions to v0.3.15
> [HELM] - Release v0.3.15

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the helm chart for the v0.3.16 release - this includes a bug fix the secrets in providers
> [HELM] - Release for v0.3.16

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Adding the changes for the helm release
> [HELM] - Release v0.3.17

- pkg/controller/configuration/ensure.go
- pkg/utils/jobs/jobs.go
Adding any labels found in the Configuration into the Watcher and terraform jobs
> [FEATURE] - Include Configuration Labels

- charts/terranetes-controller/values.yaml
Updating the version tag of the Checkov container
> [IMAGES] - Checkov Image Version

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- images/Dockerfile.cli
- images/Dockerfile.controller
- images/Dockerfile.executor
Moving the version across the board to v1.20
> [BUILD] - Golang Version 1.19-1.20

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the versions in the helm chart
> [HELM] - Release v0.3.19

- pkg/controller/configuration/delete.go
Currently you can get into a pickle if the namespace is deleted 'before' the Configurations are removed. This is due to the controller being unable to create a watcher in namespace to witness the deletion. With this PR we check the current status to ensure watcher is not created when a namespace is in a terminating phase. This user will have to rely on the Configuration status only
> [FEATURE] - Check Namespace Status

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the versions for the release
> [HELM] - Release v0.3.20

- pkg/handlers/namespaces/validation.go
- pkg/handlers/namespaces/validation_test.go
> [BUGFIX] - Terranetes Namespace Error Message

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
> [HELM] - Release v0.3.21

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
> [HELM] - Release v0.3.22

- .github/workflows/e2e.yaml
Adding the run id to the artifact name to ensure we dont have conflicting uploads
> [BUILD] - E2E Artifact Context ID

- test/e2e/assets/terraform/dummy/main.tf
Adding a dummy terraform module for use with the E2E
> [E2E] - Dummy Terraform Module

- .github/workflows/e2e.yaml
Bumping the version of the kubernetes being used in the E2E
> [BUILD] - Kubernetes E2E Version 1.26

- pkg/controller/configuration/delete.go
- test/e2e/check-suite.sh
- test/e2e/integration/clean-protection.bats
- test/e2e/integration/protection.bats
- test/e2e/integration/setup.bats
Added an E2E to ensure the namespace protection webhook is working
> [E2E] - Namespace Protection

- cmd/step/main.go
- test/e2e/check-suite.sh
- test/e2e/integration/custom-state-backend.bats
Adding a E2E to ensure the custom backend always works
> [E2E] - Custom Backend Testing

- examples/provider.yaml
- pkg/handlers/providers/validation.go
- pkg/handlers/providers/validation_test.go
Removing the constraint around the name of the provider to open up more availability
> [FEATURE] - Remove Provider Constraint

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the values for the helm release
> [HELM] - Release for v0.3.23

- examples/configuration.yaml
- test/e2e/integration/cloud/aws/confirm.bats
- test/e2e/integration/cloud/aws/plan.bats
Bumping the version of the module to take into account the AWS's default block of ACL's
> [E2E] - Bumping Terraform Module Version (Disabled ACLs)

- cmd/source/source.go
- pkg/assets/job.yaml.tpl
- pkg/utils/env.go
- pkg/utils/env_test.go
No matter what i try the goexec for git config refuses to work; something isn't getting parsed correctly in the exec. For the life of me I can't workout what
> [BUGFIX] - HTTP Authentication for Private Repositories

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the values for the helm release
> [HELM] - Release v0.3.24

- test/e2e/assets/terraform/dummy/main.tf
Adding a sentence variable to the dummay module which is used for testing purposes
> [E2E] - Adding Inputs to Dummy Module

- pkg/assets/preload.yaml.tpl
Adjusting in the clean up of preload jobs frpm 6 hours to 3
> [FEATURE] - Preload Cleanup Time

- pkg/controller/preload/ensure.go
- pkg/controller/preload/reconcile_test.go
Nothing major here, just changing the wording when a successful preload has finished
> [BUILD] - Changing the Condition on Successful Preload

- pkg/utils/preload/eks/loader.go
Adjusting some of the descriptions on the EKS loader data
> [BUILD] - Adjusting the EKS Decriptions on Context Loader

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the values in the chart
> [HELM] - Releace v0.6.0 for App Version v0.3.25

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/templates/providers.yaml
- charts/terranetes-controller/values.yaml
Allowing the user to define the preload configuration via the helm values
> [HELM] - Exposing Provider Preload Configuration

- pkg/apis/terraform/v1alpha1/context_types.go
- pkg/controller/configuration/ensure.go
- pkg/controller/configuration/reconcile.go
- pkg/controller/configuration/reconcile_test.go
We were converting to String() rather than taking the raw json, causing a issue when passing to the terraform
> [BUGFIX] - Context ValueFrom Complex Type Bug

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
> [HELM] - Release for v0.3.26

- pkg/utils/preload/eks/loader.go
Providing the cluster security group as a list as well
> [BUILD] - EKS Security Group List

- pkg/cmd/preload/context.go
- pkg/utils/preload/eks/helper.go
- pkg/utils/preload/eks/loader.go
Adding additional details in relation to the preloading of data for AWS
> [BUILD] - Additional Details for AWS Preload

- pkg/utils/preload/eks/loader.go
Adding the OIDC Arn to the eks preload details
> [PRELOAD] - Adding EKS OIDC ARN

- pkg/controller/configuration/delete.go
We were not taking the retry label into the account when building the deletion, so the `tnctl retry` command would not work when in in the Delection state
> [BUGFIX] - Deletion Retries Labels

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Adding the values for the release
> [HELM] - Release v0.3.27

- images/Dockerfile.cli
- images/Dockerfile.controller
- images/Dockerfile.executor
Bumping the base images of the executor and controller
> [BUILD] - Bumping Base Images to Alpine 3.18

- .github/workflows/release.yaml
Someone has added an policy in our Azure account forcing a number of requirements
> [E2E] - Bypassing Azure in E2E

- cmd/source/source.go
The current implementation requires with a GIT_USERNAME and GIT_PASSWORD or SSH_KEY. There is no means to support a single token. This has been largely driven after an issue surfaced with Azure Devops
```shell 
kubectl create secret generic auth --from-literal=GIT_PASSWORD=PAT
```
Use case: **Azure Devops**
* I had a private project and repository under:  https://gambol99@dev.azure.com/gambol99/terranetes-controller/_git/e2e
* I had create a PAT with `read` permissions
* I had create a authentication secret in the namespace via kubectl create secret generic auth --from-literal=GIT_PASSWORD=PAT
* I had updated the `spec.auth.name` to point to the secret
* As per https://stackoverflow.com/questions/53106546/cannot-clone-git-from-azure-devops-using-pat I rewrote the URL to …
> [FEATURE] - Support Git Token in Authentication

- charts/terranetes-controller/crds/terraform.appvia.io_providers.yaml
- pkg/apis/terraform/v1alpha1/provider_types.go
- pkg/register/assets.go
Fixing the nonsense on the field description
> [DOCS] - Fixing API CRD Description

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the versions for the release
> [HELM] - Release v0.3.28

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Updating the values to reflect the release
> [HELM] - Release v0.3.29

- pkg/controller/configuration/delete_test.go
The bug was fix in another [PR](https://github.com/appvia/terranetes-controller/pull/801), i'm just adding a unit test to ensure it doesn't break again
> [TESTS] - Update Configuration Variables On Deletion

- pkg/controller/configuration/controller.go
There have been occasions when the namespace cache goes out of whack; given it's only saving a few milliseconds, backoff off into the API isn't a bad idea when not found
> [BUGFIX] - Namespace Caching Issue

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the values for the release
> [HELM] - Release for v0.3.30

- pkg/controller/preload/ensure.go
- pkg/controller/preload/metrics.go
Adding metrics for alert events around preload controller and jobs
> [TELEMETRY] - Adding Metrics for Preloading

- pkg/handlers/contexts/validation_test.go
Adding additional tests for Context resources
> [TEST] - Validation Handler for Contexts

- pkg/handlers/namespaces/validation_test.go
Adding additional checks to the namespace validation
> [TESTS] - Namespace Validation

- pkg/utils/preload/eks/helper_test.go
Adding unit tests to the preload helper file
> [TESTS] - Preload Helper

- charts/terranetes-controller/Chart.yaml
> [HELM] - Support Provider Configuration

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the values for the release
> [HELM] - Release v0.3.31

- charts/terranetes-controller/crds/terraform.appvia.io_cloudresources.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_configurations.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_revisions.yaml
- pkg/apis/terraform/v1alpha1/revision_types.go
- pkg/assets/assets_test.go
- pkg/cmd/tnctl/create/assets/assets_test.go
- pkg/cmd/tnctl/create/revision.go
- pkg/register/assets.go
Permit the user to indicate that default variables can be injected
> [FEATURE] - Enable Default Variables Injection

- pkg/cmd/tnctl/create/configuration/build.go
- pkg/cmd/tnctl/create/create.go
- pkg/cmd/tnctl/create/workflow/workflow.go
- pkg/cmd/tnctl/search/search.go
- pkg/cmd/tnctl/tnctl.go
Moving a couple commands under create to reduce the verbage
> [CLI] - Moving Commands Under Create

- pkg/cmd/tnctl/convert/configuration.go
- pkg/cmd/tnctl/create/configuration/build.go
- pkg/cmd/tnctl/create/create.go
- pkg/cmd/tnctl/create/workflow/workflow.go
- pkg/cmd/tnctl/search/search.go
- pkg/cmd/tnctl/tnctl.go
- pkg/controller/configuration/ensure.go
- pkg/utils/terraform/utils.go
Allowing the checkov framework to be overriden
> [BUILD] - Allowing Framework to be Overriden

- charts/terranetes-controller/crds/terraform.appvia.io_plans.yaml
- pkg/apis/terraform/v1alpha1/plan_types.go
- pkg/register/assets.go
Fixing up the json tags on the fields
> [APIS] - Fixing Revision JSON Tags

- pkg/cmd/tnctl/create/assets/tnctl.revision.yaml.tpl
Adding a default to the template to ensure we always have thing set
> [BUGFIX] - Revision Template Plan Name Default

- pkg/cmd/tnctl/verify/revision.go
Currently due to the os.Exit(1) the temp directory when using tnctl verify revision is not be deleted when checks fails. This PR fixes the issues
> [BUGFIX] - Fix Deletion of Temporary Directory

- test/e2e/integration/cloudresource.bats
Fixing up the E2E checks to ensure the feature works as expected
> [E2E] - Cloud Resource E2E

- .github/workflows/release.yaml
- test/e2e/integration/cloud/azurerm/provider.bats
Adding back integration testing for Azure
> [E2E] - Azure Integration Testing

- .github/workflows/versions.yaml
Fixing up the job to pull in the image it was breaking builds
> [IMAGES] - Fixing Checkov Image Automation

- charts/terranetes-controller/crds/terraform.appvia.io_configurations.yaml
- pkg/apis/terraform/v1alpha1/configuration_types.go
- pkg/register/assets.go
Adding the drift detection flag to the output of kubectl to indicate the status
> [CLI] - Adding Drift Detection to Columns

- .gitignore
- pkg/cmd/tnctl/convert/cloudresource.go
- pkg/cmd/tnctl/convert/configuration.go
- pkg/cmd/tnctl/convert/revision.go
- pkg/cmd/tnctl/create/cloudresource.go
- pkg/cmd/tnctl/create/create.go
- pkg/cmd/tnctl/verify/revision.go
Adding to the tnctl cli the ability to provision a cloud resource
> [FEATURE] - Create CloudResource Command

- pkg/cmd/tnctl/convert/configuration.go
Was using the wrong name for the terraform input
> [BUGFIX] - Fixing the Variable Keys

- pkg/cmd/tnctl/verify/revision.go
Fixing up the warnings to be consistent
> [BUGFIX] - Warning Message on Validation

- pkg/apis/terraform/v1alpha1/revision_types.go
- pkg/cmd/tnctl/convert/revision.go
- pkg/cmd/tnctl/create/cloudresource.go
- pkg/utils/yaml.go
- pkg/utils/yaml_test.go
Fixing up elements and removing the dependency on the convert when creating a cloud resource
> [BUGFIX] - Create Cloud Resource

- pkg/apis/terraform/v1alpha1/revision_types.go
- pkg/cmd/tnctl/convert/revision.go
- pkg/cmd/tnctl/create/cloudresource.go
- pkg/cmd/tnctl/describe/describe.go
- pkg/utils/yaml.go
- pkg/utils/yaml_test.go
Fixing up the labeling issue on the describe command
> [BUGFIX] - Fixing Describe Command

- pkg/cmd/tnctl/verify/revision.go
Allowing the user to specify a relative path
> [CLI] - Verification Relative Path

- pkg/utils/preload/eks/loader.go
Adding some additional values to the preloading
> [FEATURE] - Additional EKS Preload Values

- pkg/cmd/tnctl/create/cloudresource.go
- pkg/cmd/tnctl/create/cloudresource_test.go
Adding the create cloudresource unit tests
> [TESTS] - Create Cloud Resource

- charts/terranetes-controller/values.yaml
Fixing up the spelling mistake in the helm chart
> [HELM] - Fixing Spelling Mistake

- .github/CODEOWNERS
> [BUILD] - Code Owners File

- examples/cloudresource.yaml
- examples/configuration.yaml
- examples/revision.yaml
Updating the examples for the revisions and the cloud resource
> [DOCS] - Adding Examples

- test/e2e/check-suite.sh
Fixing the issue with the exit 1
> [E2E] - Fixing Diagnostics

- test/e2e/integration/error-handler.bats
Don't need the brackets anymore
> [E2E] - Fixing Typo

- examples/cloudresource.yaml
- examples/revision.yaml
Updating the examples in the repository
> [DOCS] - Updating Examples

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the charts for the helm release
> [HELM] - Helm Release v0.4.0

- .github/workflows/e2e.yaml
Updating the kubectl and kind version to the latest
> [E2E] - Updating E2E Kind Version

- test/e2e/check-suite.sh
Fixing the reference to the debug bucket
> [E2E] - Fixing Debug Bucket

- .github/workflows/release.yaml
We need a new subscription to run the e2e in - will need to consult the aboves
> [E2E] - Dropping Azure

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the version of the chart
> [HELM] - Release v0.4.1

- .github/workflows/release.yaml
Removing the requirement for e2e-azure
> [E2E] - Fixing Dependency

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the values for the release
> [HELM] - Release v0.4.2

- charts/terranetes-controller/Chart.yaml
Fixing an issue on the chart release
> [HELM] - Release v0.7.3 Helm Chart (version: 0.4.2)

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/templates/providers.yaml
Fixing up the chart due to a templating issue
> [HELM] - Chart Update

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
> [HELM] - Release v0.4.3

- charts/terranetes-controller/values.yaml
- pkg/server/server.go
Not sure why this was the way it was - but the electon had been switched off
> [BUGFIX] - Adding Controller Election

- test/e2e/integration/setup.bats
We need to ensure multiple replicas are running
> [E2E] - Ensure Multiple Replicas in Testing

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the numbers for the release
> [HELM] - Release v0.4.4 (helm 0.7.6)

- Makefile
Fixing up the makefile and the typo
> [BUILD] - Makefile Typo

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the helm values for a maintenace release
> [HELM] - Release 0.4.5

- pkg/utils/terraform/utils_test.go
Adding a additional provider tests
> [TESTS] - Additional Provider Tests

- pkg/cmd/tnctl/approve/approve_test.go
- pkg/cmd/tnctl/convert/configuration_test.go
- pkg/cmd/tnctl/create/cloudresource_test.go
- pkg/cmd/tnctl/logs/logs_test.go
- pkg/cmd/tnctl/state/list_test.go
- pkg/controller/cloudresource/delete_test.go
- pkg/controller/cloudresource/reconcile_test.go
- pkg/controller/configuration/delete_test.go
- pkg/controller/configuration/reconcile_test.go
- pkg/controller/drift/reconcile_test.go
- pkg/controller/plan/reconcile_test.go
- pkg/controller/preload/reconcile_test.go
- pkg/controller/provider/reconcile_test.go
- pkg/controller/revision/delete_test.go
- pkg/controller/revision/reconcile_test.go
- pkg/utils/preload/eks/loader_test.go
Removing references to deprecated apis
> [BUILD] - Removing Deprecated

- .github/workflows/versions.yaml
fix: there was a typo in the bash script
> [FIX] - CI Images Workflow

- cmd/controller/main.go
- pkg/controller/expire/controller.go
- pkg/controller/expire/ensure.go
- pkg/controller/expire/reconcile.go
- pkg/controller/expire/reconcile_test.go
- pkg/server/server.go
- pkg/server/types.go
- test/fixtures/revision.go
Adding the ability to garbage collection on revision which are not used have expired
> [FEATURE] - Revision Expiration Controller

- charts/terranetes-controller/values.yaml
This reverts commit c6469cd3ffdaa4de6cc815771d4a0f588e98319c.
> Revert "[IMAGES] - Terraform Image Update (#1205)"

- hack/create-development.sh
- test/e2e/check-suite.sh
- test/e2e/lib/helper.bash
Updating the bash scripts to use 'env' to pick up on the bash location
> [BUILD] - Update Bash Scripts

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the versions in the helm chart
> [HELM] - Release v0.4.6

- images/Dockerfile.cli
- images/Dockerfile.controller
- images/Dockerfile.executor
Updating the base images for the controller, executor and the cli
> [IMAGES] - Base Images

- .github/workflows/ci.yaml
- .golangci.yml
Bumping the version of golang in the golangci-lint
> [BUILD] - Golang Version

- Makefile
Allow customizing the registry and build platform when running the Makefile.
> Allow custom registry and platform on Makefile

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Updating the versions to cut the latest release
> [HELM] - Release v0.4.7

- .github/workflows/e2e.yaml
- .github/workflows/images.yaml
- .github/workflows/release.yaml
Updating the workflows to use the latest versions and fixing the deprecated use of output variables
> [BUILD] - Github Workflows

- .github/workflows/images.yaml
Used the wrong environment variable in the workflow
> [BUILD] - Workflow

- .github/workflows/versions.yaml
Removing the suffix of pyston from the image names
> [BUILD] - Checkov Image Update

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the numbers for the 0.4.8 release
> [HELM] - Release v0.4.8

- pkg/assets/job.yaml.tpl
- pkg/controller/configuration/reconcile_test.go
Removing the color from the terraform output
> [FEATURE] - Terraform Output

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping to versions within the chart
> [HELM] - Release 0.4.9

- .github/workflows/develop.yaml
- .github/workflows/latest.yaml
- .github/workflows/release.yaml
Updating the workflow permission
> [BUILD] - Workflow Permisions

- cmd/step/main.go
- pkg/assets/job.yaml.tpl
- pkg/controller/configuration/delete.go
- pkg/controller/configuration/ensure.go
- pkg/controller/configuration/reconcile_test.go
- pkg/utils/jobs/jobs.go
- test/e2e/check-suite.sh
- test/e2e/integration/custom-state-backend.bats
- test/e2e/integration/destroy.bats
- test/e2e/integration/infracost.bats
- test/e2e/integration/plan.bats
When we moved to passing the terraform plan via secret to the apply, a number of things needed fixing"
> [BUGFIX] - Plan & Apply

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the values in the helm chart for the release
> [HELM] - Release v0.4.10

- .github/workflows/latest.yaml
Fixing up the permissions on the chart release
> [BUILD] - Workflow Permissions Charts

- charts/terranetes-controller/Chart.yaml
There was an permissions error in the workflow stopping the release to complete
> [HELM] - Release v0.4.10 (Retry)

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the versions in order to release the assets
> [HELM] - Release v0.7.14 (Application 0.4.11)

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/templates/deployment.yaml
Ordering the command line flags alphabetically
> [HELM] - Deployment Template Fix

- charts/terranetes-controller/crds/terraform.appvia.io_configurations.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_policies.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_providers.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_revisions.yaml
- pkg/apis/terraform/v1alpha1/configuration_types.go
- pkg/controller/configuration/ensure.go
- pkg/utils/jobs/jobs.go
Adds support for setting a raw string of tfvars in the configuration CRD.
> Add support for raw tfvars to Configuration CRD

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the values for the release
> [HELM] - Release 0.4.12

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the various values for the release
> [HELM] - Release v0.4.13

- Makefile
- charts/terranetes-controller/crds/terraform.appvia.io_cloudresources.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_configurations.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_contexts.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_plans.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_policies.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_providers.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_revisions.yaml
- pkg/register/assets.go
The schema generation was not run when the tfvars was added causing the field not to exist
> [FIX] - CRD Registration

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the various numbers for the release
> [HELM] - Release v0.4.19

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
> [HELM] - Release v0.4.15

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the versions for the release
> [HELM] - Release v0.4.16

- pkg/assets/job.yaml.tpl
Allowing the administrator to use the service account in the Provider regardless of the credentials type
> [FEATURE] - Provider Service Account

- charts/terranetes-controller/values.yaml
- cmd/controller/main.go
- pkg/assets/job.yaml.tpl
- pkg/controller/configuration/controller.go
- pkg/controller/configuration/delete.go
- pkg/controller/configuration/ensure.go
- pkg/controller/configuration/reconcile_test.go
- pkg/server/server.go
- pkg/server/types.go
- pkg/utils/jobs/jobs.go
Currently we are using the hashicorp image and binary, this PR changes the default implementation to opentofu
> [FEATURE] - Switching to Opentofu

- charts/terranetes-controller/templates/deployment.yaml
- charts/terranetes-controller/values.yaml
Bumping the version of the infracost image to infracost/infracost:ci-0.10.39
> [IMAGES] - Infracosts Version ci-0.10.39

- charts/terranetes-controller/templates/deployment.yaml
- charts/terranetes-controller/values.yaml
Bumping the version of check image to 3.2.298
> [IMAGES] - Checkov

- images/Dockerfile.cli
- images/Dockerfile.controller
- images/Dockerfile.executor
Updating the alpine images to 3.20.3 from 3.19
> [FEATURE] - Alpine Image 3.20.3

- charts/terranetes-controller/Chart.yaml
Bumping the numbers to publish a release
> [HELM] - Release v0.5.1 (v0.8.1)

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the version for the next release
> [HELM] - 0.5.4 Release

- images/Dockerfile.cli
- images/Dockerfile.controller
- images/Dockerfile.executor
Bumping the images for Alpine base image
> [IMAGES] - Alpine Images

- images/Dockerfile.cli
- images/Dockerfile.controller
- images/Dockerfile.executor
Bumping the version of the image builds to 1.24
> [BUILD] - Golang 1.24

- charts/terranetes-controller/crds/terraform.appvia.io_cloudresources.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_configurations.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_contexts.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_plans.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_policies.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_providers.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_revisions.yaml
- pkg/register/assets.go
Rerunning the make apis having bumped to a later version of the code
generator
> [BUILD] - Generate APIs

- charts/terranetes-controller/Chart.yaml
- charts/terranetes-controller/values.yaml
Bumping the values for the next release
> [HELM] - Release v0.5.6

- charts/terranetes-controller/crds/terraform.appvia.io_cloudresources.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_configurations.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_contexts.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_plans.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_policies.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_providers.yaml
- charts/terranetes-controller/crds/terraform.appvia.io_revisions.yaml
- pkg/register/assets.go
Rerunning the controller generation makefile stages to render the
changes, which in this case it marginal
> [BUILD] - Controller Runtime Update
